(define (problem gripper-099-heavy)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 1)
    (= (ball-cost ball2) 1)
    (= (ball-cost ball3) 1)
    (= (ball-cost ball4) 1)
    (= (ball-cost ball5) 1)
    (= (ball-cost ball6) 1)
    (= (ball-cost ball7) 1)
    (= (ball-cost ball8) 1)
    (= (ball-cost ball9) 1)
    (= (ball-cost ball10) 1)
    (= (ball-cost ball11) 10)
    (= (ball-cost ball12) 10)
    (= (ball-cost ball13) 10)
    (= (ball-cost ball14) 10)
    (at-robby room3)
    (free left)
    (free right)
    (at ball1 room1)
    (at ball2 room3)
    (at ball3 room1)
    (at ball4 room3)
    (at ball5 room1)
    (at ball6 room1)
    (at ball7 room2)
    (at ball8 room0)
    (at ball9 room0)
    (at ball10 room0)
    (at ball11 room0)
    (at ball12 room3)
    (at ball13 room2)
    (at ball14 room0)
  )

  (:goal
    (and
      (at ball1 room2)
      (at ball2 room0)
      (at ball3 room2)
      (at ball4 room1)
      (at ball5 room0)
      (at ball6 room3)
      (at ball7 room1)
      (at ball8 room2)
      (at ball9 room3)
      (at ball10 room2)
      (at ball11 room1)
      (at ball12 room2)
      (at ball13 room3)
      (at ball14 room2)
    )
  )

  (:metric minimize (total-cost))
)
