(define (problem gripper-070-heavy)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 1)
    (= (ball-cost ball2) 1)
    (= (ball-cost ball3) 1)
    (= (ball-cost ball4) 1)
    (= (ball-cost ball5) 1)
    (= (ball-cost ball6) 1)
    (= (ball-cost ball7) 1)
    (= (ball-cost ball8) 1)
    (= (ball-cost ball9) 1)
    (= (ball-cost ball10) 1)
    (= (ball-cost ball11) 1)
    (= (ball-cost ball12) 10)
    (= (ball-cost ball13) 10)
    (= (ball-cost ball14) 10)
    (= (ball-cost ball15) 10)
    (at-robby room3)
    (free left)
    (free right)
    (at ball1 room3)
    (at ball2 room1)
    (at ball3 room2)
    (at ball4 room1)
    (at ball5 room1)
    (at ball6 room0)
    (at ball7 room0)
    (at ball8 room1)
    (at ball9 room2)
    (at ball10 room2)
    (at ball11 room3)
    (at ball12 room0)
    (at ball13 room0)
    (at ball14 room0)
    (at ball15 room1)
  )

  (:goal
    (and
      (at ball1 room0)
      (at ball2 room3)
      (at ball3 room1)
      (at ball4 room0)
      (at ball5 room2)
      (at ball6 room1)
      (at ball7 room3)
      (at ball8 room0)
      (at ball9 room0)
      (at ball10 room0)
      (at ball11 room1)
      (at ball12 room2)
      (at ball13 room2)
      (at ball14 room2)
      (at ball15 room2)
    )
  )

  (:metric minimize (total-cost))
)
