(define (problem blocksworld-problem)
    (:domain blocksworld)
    (:objects block-a block-b block-c)
    (:init
        (ontable block-a)
        (ontable block-b)
        (ontable block-c)
        (clear block-a)
        (clear block-b)
        (clear block-c)
        (handempty)
    )
    (:goal (and (on block-a block-b) (on block-b block-c)))
)
