(define (problem satellite-ipc-008-inverse)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 - instrument
    image0 spectrograph3 thermograph1 thermograph2 - mode
    groundstation1 phenomenon5 phenomenon8 phenomenon9 phenomenon12 phenomenon13 phenomenon14 planet11 star0 star2 star3 star4 star6 star7 star10 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation1) 15)
    (= (target-cost phenomenon5) 14)
    (= (target-cost phenomenon8) 13)
    (= (target-cost phenomenon9) 12)
    (= (target-cost phenomenon12) 11)
    (= (target-cost phenomenon13) 10)
    (= (target-cost phenomenon14) 9)
    (= (target-cost planet11) 8)
    (= (target-cost star0) 7)
    (= (target-cost star2) 6)
    (= (target-cost star3) 5)
    (= (target-cost star4) 4)
    (= (target-cost star6) 3)
    (= (target-cost star7) 2)
    (= (target-cost star10) 1)
    (= (instrument-cost instrument0) 10)
    (= (instrument-cost instrument1) 9)
    (= (instrument-cost instrument2) 8)
    (= (instrument-cost instrument3) 7)
    (= (instrument-cost instrument4) 6)
    (= (instrument-cost instrument5) 5)
    (= (instrument-cost instrument6) 4)
    (= (instrument-cost instrument7) 3)
    (= (instrument-cost instrument8) 2)
    (= (instrument-cost instrument9) 1)
    (= (satellite-move-cost satellite0) 4)
    (= (satellite-move-cost satellite1) 3)
    (= (satellite-move-cost satellite2) 2)
    (= (satellite-move-cost satellite3) 1)
    (supports instrument0 thermograph1)
    (supports instrument0 image0)
    (calibration-target instrument0 star3)
    (supports instrument1 spectrograph3)
    (supports instrument1 thermograph2)
    (supports instrument1 thermograph1)
    (calibration-target instrument1 star2)
    (supports instrument2 spectrograph3)
    (calibration-target instrument2 star4)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 phenomenon14)
    (supports instrument3 thermograph2)
    (supports instrument3 image0)
    (calibration-target instrument3 groundstation1)
    (supports instrument4 thermograph1)
    (calibration-target instrument4 star4)
    (supports instrument5 thermograph2)
    (supports instrument5 thermograph1)
    (supports instrument5 spectrograph3)
    (calibration-target instrument5 star0)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (on-board instrument5 satellite1)
    (power-avail satellite1)
    (pointing satellite1 star4)
    (supports instrument6 thermograph1)
    (supports instrument6 thermograph2)
    (calibration-target instrument6 star3)
    (supports instrument7 thermograph2)
    (supports instrument7 thermograph1)
    (supports instrument7 image0)
    (calibration-target instrument7 star0)
    (on-board instrument6 satellite2)
    (on-board instrument7 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star6)
    (supports instrument8 image0)
    (calibration-target instrument8 star3)
    (supports instrument9 spectrograph3)
    (supports instrument9 thermograph1)
    (supports instrument9 image0)
    (calibration-target instrument9 star4)
    (on-board instrument8 satellite3)
    (on-board instrument9 satellite3)
    (power-avail satellite3)
    (pointing satellite3 phenomenon5)
  )

  (:goal
    (and
      (have-image phenomenon5 thermograph1)
      (have-image star6 thermograph1)
      (have-image star7 spectrograph3)
      (have-image phenomenon8 image0)
      (have-image phenomenon9 image0)
      (have-image star10 spectrograph3)
      (have-image planet11 thermograph2)
      (have-image phenomenon12 image0)
      (have-image phenomenon13 thermograph1)
      (have-image phenomenon14 thermograph2)
    )
  )

  (:metric minimize (total-cost))
)
