(define (problem satellite-ipc-019-inverse)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 instrument23 instrument24 - instrument
    image4 image5 infrared2 infrared3 infrared7 spectrograph0 spectrograph6 thermograph1 - mode
    groundstation0 groundstation4 phenomenon5 phenomenon7 phenomenon8 phenomenon11 phenomenon13 phenomenon20 phenomenon24 planet9 planet15 planet17 planet21 planet22 star1 star2 star3 star6 star10 star12 star14 star16 star18 star19 star23 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 25)
    (= (target-cost groundstation4) 24)
    (= (target-cost phenomenon5) 23)
    (= (target-cost phenomenon7) 22)
    (= (target-cost phenomenon8) 21)
    (= (target-cost phenomenon11) 20)
    (= (target-cost phenomenon13) 19)
    (= (target-cost phenomenon20) 18)
    (= (target-cost phenomenon24) 17)
    (= (target-cost planet9) 16)
    (= (target-cost planet15) 15)
    (= (target-cost planet17) 14)
    (= (target-cost planet21) 13)
    (= (target-cost planet22) 12)
    (= (target-cost star1) 11)
    (= (target-cost star2) 10)
    (= (target-cost star3) 9)
    (= (target-cost star6) 8)
    (= (target-cost star10) 7)
    (= (target-cost star12) 6)
    (= (target-cost star14) 5)
    (= (target-cost star16) 4)
    (= (target-cost star18) 3)
    (= (target-cost star19) 2)
    (= (target-cost star23) 1)
    (= (instrument-cost instrument0) 25)
    (= (instrument-cost instrument1) 24)
    (= (instrument-cost instrument2) 23)
    (= (instrument-cost instrument3) 22)
    (= (instrument-cost instrument4) 21)
    (= (instrument-cost instrument5) 20)
    (= (instrument-cost instrument6) 19)
    (= (instrument-cost instrument7) 18)
    (= (instrument-cost instrument8) 17)
    (= (instrument-cost instrument9) 16)
    (= (instrument-cost instrument10) 15)
    (= (instrument-cost instrument11) 14)
    (= (instrument-cost instrument12) 13)
    (= (instrument-cost instrument13) 12)
    (= (instrument-cost instrument14) 11)
    (= (instrument-cost instrument15) 10)
    (= (instrument-cost instrument16) 9)
    (= (instrument-cost instrument17) 8)
    (= (instrument-cost instrument18) 7)
    (= (instrument-cost instrument19) 6)
    (= (instrument-cost instrument20) 5)
    (= (instrument-cost instrument21) 4)
    (= (instrument-cost instrument22) 3)
    (= (instrument-cost instrument23) 2)
    (= (instrument-cost instrument24) 1)
    (= (satellite-move-cost satellite0) 5)
    (= (satellite-move-cost satellite1) 4)
    (= (satellite-move-cost satellite2) 3)
    (= (satellite-move-cost satellite3) 2)
    (= (satellite-move-cost satellite4) 1)
    (supports instrument0 infrared2)
    (supports instrument0 image4)
    (calibration-target instrument0 groundstation0)
    (supports instrument1 spectrograph0)
    (calibration-target instrument1 star3)
    (supports instrument2 infrared3)
    (supports instrument2 thermograph1)
    (supports instrument2 spectrograph0)
    (calibration-target instrument2 star1)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 planet21)
    (supports instrument3 thermograph1)
    (supports instrument3 image5)
    (calibration-target instrument3 star1)
    (supports instrument4 spectrograph0)
    (calibration-target instrument4 star3)
    (supports instrument5 thermograph1)
    (supports instrument5 spectrograph0)
    (supports instrument5 spectrograph6)
    (calibration-target instrument5 groundstation4)
    (supports instrument6 image5)
    (supports instrument6 infrared7)
    (calibration-target instrument6 star3)
    (supports instrument7 spectrograph6)
    (supports instrument7 thermograph1)
    (supports instrument7 spectrograph0)
    (calibration-target instrument7 star2)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (on-board instrument5 satellite1)
    (on-board instrument6 satellite1)
    (on-board instrument7 satellite1)
    (power-avail satellite1)
    (pointing satellite1 planet21)
    (supports instrument8 infrared3)
    (supports instrument8 infrared7)
    (calibration-target instrument8 star1)
    (supports instrument9 spectrograph0)
    (calibration-target instrument9 star3)
    (supports instrument10 image4)
    (supports instrument10 infrared7)
    (supports instrument10 image5)
    (calibration-target instrument10 groundstation4)
    (supports instrument11 infrared2)
    (calibration-target instrument11 star2)
    (supports instrument12 thermograph1)
    (calibration-target instrument12 star3)
    (supports instrument13 infrared3)
    (calibration-target instrument13 star2)
    (on-board instrument8 satellite2)
    (on-board instrument9 satellite2)
    (on-board instrument10 satellite2)
    (on-board instrument11 satellite2)
    (on-board instrument12 satellite2)
    (on-board instrument13 satellite2)
    (power-avail satellite2)
    (pointing satellite2 phenomenon5)
    (supports instrument14 thermograph1)
    (supports instrument14 infrared2)
    (calibration-target instrument14 groundstation4)
    (supports instrument15 infrared2)
    (calibration-target instrument15 star1)
    (supports instrument16 image4)
    (supports instrument16 spectrograph6)
    (calibration-target instrument16 star2)
    (supports instrument17 image4)
    (supports instrument17 infrared7)
    (supports instrument17 image5)
    (calibration-target instrument17 groundstation0)
    (supports instrument18 image4)
    (supports instrument18 spectrograph6)
    (calibration-target instrument18 star2)
    (supports instrument19 infrared3)
    (supports instrument19 infrared7)
    (supports instrument19 spectrograph6)
    (calibration-target instrument19 star3)
    (supports instrument20 infrared3)
    (supports instrument20 infrared2)
    (calibration-target instrument20 star2)
    (supports instrument21 infrared2)
    (supports instrument21 thermograph1)
    (calibration-target instrument21 groundstation4)
    (on-board instrument14 satellite3)
    (on-board instrument15 satellite3)
    (on-board instrument16 satellite3)
    (on-board instrument17 satellite3)
    (on-board instrument18 satellite3)
    (on-board instrument19 satellite3)
    (on-board instrument20 satellite3)
    (on-board instrument21 satellite3)
    (power-avail satellite3)
    (pointing satellite3 phenomenon20)
    (supports instrument22 thermograph1)
    (supports instrument22 image5)
    (calibration-target instrument22 star2)
    (supports instrument23 infrared7)
    (supports instrument23 thermograph1)
    (calibration-target instrument23 star3)
    (supports instrument24 infrared3)
    (supports instrument24 spectrograph0)
    (calibration-target instrument24 groundstation0)
    (on-board instrument22 satellite4)
    (on-board instrument23 satellite4)
    (on-board instrument24 satellite4)
    (power-avail satellite4)
    (pointing satellite4 star14)
  )

  (:goal
    (and
      (pointing satellite0 planet17)
      (have-image phenomenon5 infrared7)
      (have-image phenomenon5 image4)
      (have-image phenomenon7 thermograph1)
      (have-image planet9 spectrograph0)
      (have-image planet9 spectrograph6)
      (have-image star10 infrared3)
      (have-image star10 spectrograph6)
      (have-image phenomenon11 infrared2)
      (have-image star12 spectrograph6)
      (have-image star12 thermograph1)
      (have-image phenomenon13 infrared7)
      (have-image phenomenon13 infrared2)
      (have-image star14 infrared2)
      (have-image planet15 infrared2)
      (have-image star16 image4)
      (have-image planet17 image5)
      (have-image planet17 image4)
      (have-image star18 infrared2)
      (have-image star19 infrared3)
      (have-image star19 thermograph1)
      (have-image phenomenon20 spectrograph0)
      (have-image planet21 infrared3)
      (have-image planet21 image5)
      (have-image planet22 infrared2)
      (have-image star23 infrared2)
      (have-image phenomenon24 spectrograph6)
      (have-image phenomenon24 image5)
    )
  )

  (:metric minimize (total-cost))
)
