(define (problem satellite-ipc-007-inverse)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 - instrument
    image0 image1 image2 image3 - mode
    groundstation0 groundstation2 groundstation4 phenomenon5 planet8 planet9 planet10 planet11 star1 star3 star6 star7 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 12)
    (= (target-cost groundstation2) 11)
    (= (target-cost groundstation4) 10)
    (= (target-cost phenomenon5) 9)
    (= (target-cost planet8) 8)
    (= (target-cost planet9) 7)
    (= (target-cost planet10) 6)
    (= (target-cost planet11) 5)
    (= (target-cost star1) 4)
    (= (target-cost star3) 3)
    (= (target-cost star6) 2)
    (= (target-cost star7) 1)
    (= (instrument-cost instrument0) 8)
    (= (instrument-cost instrument1) 7)
    (= (instrument-cost instrument2) 6)
    (= (instrument-cost instrument3) 5)
    (= (instrument-cost instrument4) 4)
    (= (instrument-cost instrument5) 3)
    (= (instrument-cost instrument6) 2)
    (= (instrument-cost instrument7) 1)
    (= (satellite-move-cost satellite0) 4)
    (= (satellite-move-cost satellite1) 3)
    (= (satellite-move-cost satellite2) 2)
    (= (satellite-move-cost satellite3) 1)
    (supports instrument0 image1)
    (supports instrument0 image3)
    (calibration-target instrument0 star1)
    (supports instrument1 image3)
    (calibration-target instrument1 groundstation0)
    (supports instrument2 image0)
    (calibration-target instrument2 groundstation2)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star6)
    (supports instrument3 image0)
    (supports instrument3 image2)
    (calibration-target instrument3 groundstation4)
    (on-board instrument3 satellite1)
    (power-avail satellite1)
    (pointing satellite1 groundstation0)
    (supports instrument4 image1)
    (supports instrument4 image0)
    (calibration-target instrument4 star1)
    (supports instrument5 image2)
    (supports instrument5 image0)
    (supports instrument5 image1)
    (calibration-target instrument5 star1)
    (on-board instrument4 satellite2)
    (on-board instrument5 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star6)
    (supports instrument6 image2)
    (supports instrument6 image1)
    (supports instrument6 image0)
    (calibration-target instrument6 groundstation4)
    (supports instrument7 image3)
    (supports instrument7 image0)
    (supports instrument7 image1)
    (calibration-target instrument7 groundstation0)
    (on-board instrument6 satellite3)
    (on-board instrument7 satellite3)
    (power-avail satellite3)
    (pointing satellite3 groundstation2)
  )

  (:goal
    (and
      (pointing satellite1 star1)
      (pointing satellite2 phenomenon5)
      (have-image phenomenon5 image0)
      (have-image star6 image1)
      (have-image star7 image0)
      (have-image planet8 image0)
      (have-image planet9 image3)
      (have-image planet10 image0)
      (have-image planet11 image2)
    )
  )

  (:metric minimize (total-cost))
)
