(define (problem gripper-008-inverse)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 ball16 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 16)
    (= (ball-cost ball2) 15)
    (= (ball-cost ball3) 14)
    (= (ball-cost ball4) 13)
    (= (ball-cost ball5) 12)
    (= (ball-cost ball6) 11)
    (= (ball-cost ball7) 10)
    (= (ball-cost ball8) 9)
    (= (ball-cost ball9) 8)
    (= (ball-cost ball10) 7)
    (= (ball-cost ball11) 6)
    (= (ball-cost ball12) 5)
    (= (ball-cost ball13) 4)
    (= (ball-cost ball14) 3)
    (= (ball-cost ball15) 2)
    (= (ball-cost ball16) 1)
    (at-robby room2)
    (free left)
    (free right)
    (at ball1 room0)
    (at ball2 room2)
    (at ball3 room0)
    (at ball4 room2)
    (at ball5 room0)
    (at ball6 room0)
    (at ball7 room2)
    (at ball8 room2)
    (at ball9 room1)
    (at ball10 room1)
    (at ball11 room0)
    (at ball12 room2)
    (at ball13 room3)
    (at ball14 room0)
    (at ball15 room3)
    (at ball16 room2)
  )

  (:goal
    (and
      (at ball1 room2)
      (at ball2 room1)
      (at ball3 room3)
      (at ball4 room1)
      (at ball5 room2)
      (at ball6 room3)
      (at ball7 room0)
      (at ball8 room3)
      (at ball9 room2)
      (at ball10 room3)
      (at ball11 room3)
      (at ball12 room0)
      (at ball13 room2)
      (at ball14 room2)
      (at ball15 room1)
      (at ball16 room1)
    )
  )

  (:metric minimize (total-cost))
)
