(define (problem gripper-079-inverse)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 15)
    (= (ball-cost ball2) 14)
    (= (ball-cost ball3) 13)
    (= (ball-cost ball4) 12)
    (= (ball-cost ball5) 11)
    (= (ball-cost ball6) 10)
    (= (ball-cost ball7) 9)
    (= (ball-cost ball8) 8)
    (= (ball-cost ball9) 7)
    (= (ball-cost ball10) 6)
    (= (ball-cost ball11) 5)
    (= (ball-cost ball12) 4)
    (= (ball-cost ball13) 3)
    (= (ball-cost ball14) 2)
    (= (ball-cost ball15) 1)
    (at-robby room2)
    (free left)
    (free right)
    (at ball1 room2)
    (at ball2 room1)
    (at ball3 room3)
    (at ball4 room0)
    (at ball5 room0)
    (at ball6 room1)
    (at ball7 room1)
    (at ball8 room2)
    (at ball9 room2)
    (at ball10 room3)
    (at ball11 room2)
    (at ball12 room1)
    (at ball13 room1)
    (at ball14 room0)
    (at ball15 room3)
  )

  (:goal
    (and
      (at ball1 room1)
      (at ball2 room0)
      (at ball3 room0)
      (at ball4 room1)
      (at ball5 room3)
      (at ball6 room2)
      (at ball7 room2)
      (at ball8 room0)
      (at ball9 room1)
      (at ball10 room2)
      (at ball11 room0)
      (at ball12 room2)
      (at ball13 room0)
      (at ball14 room2)
      (at ball15 room2)
    )
  )

  (:metric minimize (total-cost))
)
