(define (problem rovers-ipc-005-unit)
  (:domain rovers)

  (:objects
    rover0 rover1 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
    rover0store rover1store - store
    camera0 camera1 camera2 - camera
    colour high_res low_res - mode
    objective0 objective1 objective2 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 1)
    (= (sample-cost waypoint1) 1)
    (= (sample-cost waypoint2) 1)
    (= (sample-cost waypoint3) 1)
    (= (image-cost objective0) 1)
    (= (image-cost objective1) 1)
    (= (image-cost objective2) 1)
    (= (rover-cost rover0) 1)
    (= (rover-cost rover1) 1)
    (= (communicate-cost) 1)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint0)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint3)
    (visible waypoint3 waypoint1)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint3 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint3)
    (at-lander general waypoint3)
    (channel-free general)
    (at rover0 waypoint0)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-rock-analysis rover0)
    (equipped-for-imaging rover0)
    (can-traverse rover0 waypoint0 waypoint1)
    (can-traverse rover0 waypoint1 waypoint0)
    (can-traverse rover0 waypoint0 waypoint3)
    (can-traverse rover0 waypoint3 waypoint0)
    (at rover1 waypoint0)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-soil-analysis rover1)
    (equipped-for-imaging rover1)
    (can-traverse rover1 waypoint0 waypoint1)
    (can-traverse rover1 waypoint1 waypoint0)
    (can-traverse rover1 waypoint1 waypoint2)
    (can-traverse rover1 waypoint2 waypoint1)
    (can-traverse rover1 waypoint1 waypoint3)
    (can-traverse rover1 waypoint3 waypoint1)
    (on-board camera0 rover1)
    (calibration-target camera0 objective1)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on-board camera1 rover1)
    (calibration-target camera1 objective1)
    (supports camera1 colour)
    (supports camera1 high_res)
    (on-board camera2 rover0)
    (calibration-target camera2 objective1)
    (supports camera2 colour)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective0 waypoint3)
    (visible-from objective1 waypoint0)
    (visible-from objective1 waypoint1)
    (visible-from objective1 waypoint2)
    (visible-from objective2 waypoint0)
    (visible-from objective2 waypoint1)
    (visible-from objective2 waypoint2)
  )

  (:goal
    (and
      (communicated-soil-data waypoint1)
      (communicated-soil-data waypoint2)
      (communicated-rock-data waypoint0)
      (communicated-rock-data waypoint1)
      (communicated-image-data objective0 high_res)
      (communicated-image-data objective2 high_res)
      (communicated-image-data objective0 colour)
    )
  )

  (:metric minimize (total-cost))
)
