(define (problem rovers-ipc-009-unit)
  (:domain rovers)

  (:objects
    rover0 rover1 rover2 rover3 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 - waypoint
    rover0store rover1store rover2store rover3store - store
    camera0 camera1 camera2 camera3 camera4 - camera
    colour high_res low_res - mode
    objective0 objective1 objective2 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 1)
    (= (sample-cost waypoint1) 1)
    (= (sample-cost waypoint2) 1)
    (= (sample-cost waypoint3) 1)
    (= (sample-cost waypoint4) 1)
    (= (sample-cost waypoint5) 1)
    (= (sample-cost waypoint6) 1)
    (= (image-cost objective0) 1)
    (= (image-cost objective1) 1)
    (= (image-cost objective2) 1)
    (= (rover-cost rover0) 1)
    (= (rover-cost rover1) 1)
    (= (rover-cost rover2) 1)
    (= (rover-cost rover3) 1)
    (= (communicate-cost) 1)
    (visible waypoint0 waypoint5)
    (visible waypoint5 waypoint0)
    (visible waypoint0 waypoint6)
    (visible waypoint6 waypoint0)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint4)
    (visible waypoint4 waypoint1)
    (visible waypoint1 waypoint6)
    (visible waypoint6 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint2)
    (visible waypoint2 waypoint6)
    (visible waypoint6 waypoint2)
    (visible waypoint3 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint1)
    (visible waypoint1 waypoint3)
    (visible waypoint4 waypoint3)
    (visible waypoint3 waypoint4)
    (visible waypoint4 waypoint6)
    (visible waypoint6 waypoint4)
    (visible waypoint5 waypoint1)
    (visible waypoint1 waypoint5)
    (visible waypoint6 waypoint3)
    (visible waypoint3 waypoint6)
    (visible waypoint6 waypoint5)
    (visible waypoint5 waypoint6)
    (at-lander general waypoint4)
    (channel-free general)
    (at rover0 waypoint5)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-imaging rover0)
    (can-traverse rover0 waypoint5 waypoint0)
    (can-traverse rover0 waypoint0 waypoint5)
    (can-traverse rover0 waypoint5 waypoint1)
    (can-traverse rover0 waypoint1 waypoint5)
    (can-traverse rover0 waypoint5 waypoint2)
    (can-traverse rover0 waypoint2 waypoint5)
    (can-traverse rover0 waypoint5 waypoint6)
    (can-traverse rover0 waypoint6 waypoint5)
    (can-traverse rover0 waypoint1 waypoint3)
    (can-traverse rover0 waypoint3 waypoint1)
    (can-traverse rover0 waypoint1 waypoint4)
    (can-traverse rover0 waypoint4 waypoint1)
    (at rover1 waypoint2)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-rock-analysis rover1)
    (equipped-for-imaging rover1)
    (can-traverse rover1 waypoint2 waypoint0)
    (can-traverse rover1 waypoint0 waypoint2)
    (can-traverse rover1 waypoint2 waypoint1)
    (can-traverse rover1 waypoint1 waypoint2)
    (can-traverse rover1 waypoint2 waypoint5)
    (can-traverse rover1 waypoint5 waypoint2)
    (can-traverse rover1 waypoint2 waypoint6)
    (can-traverse rover1 waypoint6 waypoint2)
    (can-traverse rover1 waypoint1 waypoint3)
    (can-traverse rover1 waypoint3 waypoint1)
    (can-traverse rover1 waypoint1 waypoint4)
    (can-traverse rover1 waypoint4 waypoint1)
    (at rover2 waypoint0)
    (store-of rover2store rover2)
    (empty rover2store)
    (equipped-for-soil-analysis rover2)
    (equipped-for-imaging rover2)
    (can-traverse rover2 waypoint0 waypoint1)
    (can-traverse rover2 waypoint1 waypoint0)
    (can-traverse rover2 waypoint0 waypoint3)
    (can-traverse rover2 waypoint3 waypoint0)
    (can-traverse rover2 waypoint0 waypoint6)
    (can-traverse rover2 waypoint6 waypoint0)
    (can-traverse rover2 waypoint1 waypoint2)
    (can-traverse rover2 waypoint2 waypoint1)
    (can-traverse rover2 waypoint1 waypoint5)
    (can-traverse rover2 waypoint5 waypoint1)
    (can-traverse rover2 waypoint3 waypoint4)
    (can-traverse rover2 waypoint4 waypoint3)
    (at rover3 waypoint2)
    (store-of rover3store rover3)
    (empty rover3store)
    (equipped-for-soil-analysis rover3)
    (equipped-for-imaging rover3)
    (can-traverse rover3 waypoint2 waypoint0)
    (can-traverse rover3 waypoint0 waypoint2)
    (can-traverse rover3 waypoint2 waypoint1)
    (can-traverse rover3 waypoint1 waypoint2)
    (can-traverse rover3 waypoint2 waypoint6)
    (can-traverse rover3 waypoint6 waypoint2)
    (can-traverse rover3 waypoint0 waypoint3)
    (can-traverse rover3 waypoint3 waypoint0)
    (can-traverse rover3 waypoint0 waypoint5)
    (can-traverse rover3 waypoint5 waypoint0)
    (can-traverse rover3 waypoint1 waypoint4)
    (can-traverse rover3 waypoint4 waypoint1)
    (on-board camera0 rover3)
    (calibration-target camera0 objective2)
    (supports camera0 colour)
    (supports camera0 low_res)
    (on-board camera1 rover0)
    (calibration-target camera1 objective2)
    (supports camera1 colour)
    (on-board camera2 rover0)
    (calibration-target camera2 objective0)
    (supports camera2 low_res)
    (on-board camera3 rover2)
    (calibration-target camera3 objective0)
    (supports camera3 colour)
    (supports camera3 high_res)
    (supports camera3 low_res)
    (on-board camera4 rover1)
    (calibration-target camera4 objective1)
    (supports camera4 colour)
    (supports camera4 low_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective1 waypoint0)
    (visible-from objective1 waypoint1)
    (visible-from objective1 waypoint2)
    (visible-from objective1 waypoint3)
    (visible-from objective1 waypoint4)
    (visible-from objective1 waypoint5)
    (visible-from objective2 waypoint0)
    (visible-from objective2 waypoint1)
    (visible-from objective2 waypoint2)
    (visible-from objective2 waypoint3)
    (visible-from objective2 waypoint4)
    (visible-from objective2 waypoint5)
    (visible-from objective2 waypoint6)
  )

  (:goal
    (and
      (communicated-soil-data waypoint6)
      (communicated-soil-data waypoint4)
      (communicated-soil-data waypoint0)
      (communicated-rock-data waypoint6)
      (communicated-rock-data waypoint0)
      (communicated-rock-data waypoint3)
      (communicated-image-data objective2 low_res)
      (communicated-image-data objective2 colour)
    )
  )

  (:metric minimize (total-cost))
)
