(define (problem rovers-ipc-017-unit)
  (:domain rovers)

  (:objects
    rover0 rover1 rover2 rover3 rover4 rover5 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 - waypoint
    rover0store rover1store rover2store rover3store rover4store rover5store - store
    camera0 camera1 camera2 camera3 camera4 camera5 camera6 - camera
    colour high_res low_res - mode
    objective0 objective1 objective2 objective3 objective4 objective5 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 1)
    (= (sample-cost waypoint1) 1)
    (= (sample-cost waypoint2) 1)
    (= (sample-cost waypoint3) 1)
    (= (sample-cost waypoint4) 1)
    (= (sample-cost waypoint5) 1)
    (= (sample-cost waypoint6) 1)
    (= (sample-cost waypoint7) 1)
    (= (sample-cost waypoint8) 1)
    (= (sample-cost waypoint9) 1)
    (= (sample-cost waypoint10) 1)
    (= (sample-cost waypoint11) 1)
    (= (sample-cost waypoint12) 1)
    (= (sample-cost waypoint13) 1)
    (= (sample-cost waypoint14) 1)
    (= (image-cost objective0) 1)
    (= (image-cost objective1) 1)
    (= (image-cost objective2) 1)
    (= (image-cost objective3) 1)
    (= (image-cost objective4) 1)
    (= (image-cost objective5) 1)
    (= (rover-cost rover0) 1)
    (= (rover-cost rover1) 1)
    (= (rover-cost rover2) 1)
    (= (rover-cost rover3) 1)
    (= (rover-cost rover4) 1)
    (= (rover-cost rover5) 1)
    (= (communicate-cost) 1)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint8)
    (visible waypoint8 waypoint1)
    (visible waypoint1 waypoint11)
    (visible waypoint11 waypoint1)
    (visible waypoint1 waypoint14)
    (visible waypoint14 waypoint1)
    (visible waypoint2 waypoint6)
    (visible waypoint6 waypoint2)
    (visible waypoint2 waypoint9)
    (visible waypoint9 waypoint2)
    (visible waypoint3 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint3)
    (visible waypoint3 waypoint6)
    (visible waypoint6 waypoint3)
    (visible waypoint3 waypoint7)
    (visible waypoint7 waypoint3)
    (visible waypoint3 waypoint11)
    (visible waypoint11 waypoint3)
    (visible waypoint3 waypoint13)
    (visible waypoint13 waypoint3)
    (visible waypoint4 waypoint1)
    (visible waypoint1 waypoint4)
    (visible waypoint4 waypoint2)
    (visible waypoint2 waypoint4)
    (visible waypoint4 waypoint10)
    (visible waypoint10 waypoint4)
    (visible waypoint4 waypoint14)
    (visible waypoint14 waypoint4)
    (visible waypoint5 waypoint1)
    (visible waypoint1 waypoint5)
    (visible waypoint5 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint3)
    (visible waypoint3 waypoint5)
    (visible waypoint5 waypoint8)
    (visible waypoint8 waypoint5)
    (visible waypoint5 waypoint14)
    (visible waypoint14 waypoint5)
    (visible waypoint6 waypoint0)
    (visible waypoint0 waypoint6)
    (visible waypoint6 waypoint4)
    (visible waypoint4 waypoint6)
    (visible waypoint6 waypoint5)
    (visible waypoint5 waypoint6)
    (visible waypoint6 waypoint7)
    (visible waypoint7 waypoint6)
    (visible waypoint6 waypoint10)
    (visible waypoint10 waypoint6)
    (visible waypoint6 waypoint12)
    (visible waypoint12 waypoint6)
    (visible waypoint6 waypoint13)
    (visible waypoint13 waypoint6)
    (visible waypoint7 waypoint8)
    (visible waypoint8 waypoint7)
    (visible waypoint7 waypoint9)
    (visible waypoint9 waypoint7)
    (visible waypoint8 waypoint2)
    (visible waypoint2 waypoint8)
    (visible waypoint8 waypoint3)
    (visible waypoint3 waypoint8)
    (visible waypoint8 waypoint10)
    (visible waypoint10 waypoint8)
    (visible waypoint9 waypoint8)
    (visible waypoint8 waypoint9)
    (visible waypoint10 waypoint0)
    (visible waypoint0 waypoint10)
    (visible waypoint10 waypoint3)
    (visible waypoint3 waypoint10)
    (visible waypoint11 waypoint2)
    (visible waypoint2 waypoint11)
    (visible waypoint11 waypoint4)
    (visible waypoint4 waypoint11)
    (visible waypoint11 waypoint8)
    (visible waypoint8 waypoint11)
    (visible waypoint11 waypoint9)
    (visible waypoint9 waypoint11)
    (visible waypoint11 waypoint10)
    (visible waypoint10 waypoint11)
    (visible waypoint12 waypoint0)
    (visible waypoint0 waypoint12)
    (visible waypoint12 waypoint1)
    (visible waypoint1 waypoint12)
    (visible waypoint12 waypoint5)
    (visible waypoint5 waypoint12)
    (visible waypoint12 waypoint7)
    (visible waypoint7 waypoint12)
    (visible waypoint13 waypoint0)
    (visible waypoint0 waypoint13)
    (visible waypoint13 waypoint5)
    (visible waypoint5 waypoint13)
    (visible waypoint13 waypoint14)
    (visible waypoint14 waypoint13)
    (visible waypoint14 waypoint2)
    (visible waypoint2 waypoint14)
    (visible waypoint14 waypoint3)
    (visible waypoint3 waypoint14)
    (visible waypoint14 waypoint9)
    (visible waypoint9 waypoint14)
    (visible waypoint14 waypoint10)
    (visible waypoint10 waypoint14)
    (at-lander general waypoint13)
    (channel-free general)
    (at rover0 waypoint12)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-rock-analysis rover0)
    (can-traverse rover0 waypoint12 waypoint0)
    (can-traverse rover0 waypoint0 waypoint12)
    (can-traverse rover0 waypoint12 waypoint1)
    (can-traverse rover0 waypoint1 waypoint12)
    (can-traverse rover0 waypoint12 waypoint6)
    (can-traverse rover0 waypoint6 waypoint12)
    (can-traverse rover0 waypoint12 waypoint7)
    (can-traverse rover0 waypoint7 waypoint12)
    (can-traverse rover0 waypoint0 waypoint3)
    (can-traverse rover0 waypoint3 waypoint0)
    (can-traverse rover0 waypoint1 waypoint4)
    (can-traverse rover0 waypoint4 waypoint1)
    (can-traverse rover0 waypoint1 waypoint5)
    (can-traverse rover0 waypoint5 waypoint1)
    (can-traverse rover0 waypoint1 waypoint8)
    (can-traverse rover0 waypoint8 waypoint1)
    (can-traverse rover0 waypoint1 waypoint11)
    (can-traverse rover0 waypoint11 waypoint1)
    (can-traverse rover0 waypoint6 waypoint13)
    (can-traverse rover0 waypoint13 waypoint6)
    (can-traverse rover0 waypoint7 waypoint9)
    (can-traverse rover0 waypoint9 waypoint7)
    (at rover1 waypoint12)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-imaging rover1)
    (can-traverse rover1 waypoint12 waypoint0)
    (can-traverse rover1 waypoint0 waypoint12)
    (can-traverse rover1 waypoint12 waypoint1)
    (can-traverse rover1 waypoint1 waypoint12)
    (can-traverse rover1 waypoint12 waypoint5)
    (can-traverse rover1 waypoint5 waypoint12)
    (can-traverse rover1 waypoint12 waypoint6)
    (can-traverse rover1 waypoint6 waypoint12)
    (can-traverse rover1 waypoint0 waypoint3)
    (can-traverse rover1 waypoint3 waypoint0)
    (can-traverse rover1 waypoint0 waypoint13)
    (can-traverse rover1 waypoint13 waypoint0)
    (can-traverse rover1 waypoint1 waypoint11)
    (can-traverse rover1 waypoint11 waypoint1)
    (can-traverse rover1 waypoint1 waypoint14)
    (can-traverse rover1 waypoint14 waypoint1)
    (can-traverse rover1 waypoint5 waypoint2)
    (can-traverse rover1 waypoint2 waypoint5)
    (can-traverse rover1 waypoint5 waypoint8)
    (can-traverse rover1 waypoint8 waypoint5)
    (can-traverse rover1 waypoint6 waypoint4)
    (can-traverse rover1 waypoint4 waypoint6)
    (can-traverse rover1 waypoint6 waypoint7)
    (can-traverse rover1 waypoint7 waypoint6)
    (can-traverse rover1 waypoint6 waypoint10)
    (can-traverse rover1 waypoint10 waypoint6)
    (can-traverse rover1 waypoint11 waypoint9)
    (can-traverse rover1 waypoint9 waypoint11)
    (at rover2 waypoint5)
    (store-of rover2store rover2)
    (empty rover2store)
    (equipped-for-imaging rover2)
    (can-traverse rover2 waypoint5 waypoint1)
    (can-traverse rover2 waypoint1 waypoint5)
    (can-traverse rover2 waypoint5 waypoint2)
    (can-traverse rover2 waypoint2 waypoint5)
    (can-traverse rover2 waypoint5 waypoint6)
    (can-traverse rover2 waypoint6 waypoint5)
    (can-traverse rover2 waypoint5 waypoint8)
    (can-traverse rover2 waypoint8 waypoint5)
    (can-traverse rover2 waypoint5 waypoint13)
    (can-traverse rover2 waypoint13 waypoint5)
    (can-traverse rover2 waypoint5 waypoint14)
    (can-traverse rover2 waypoint14 waypoint5)
    (can-traverse rover2 waypoint1 waypoint0)
    (can-traverse rover2 waypoint0 waypoint1)
    (can-traverse rover2 waypoint1 waypoint4)
    (can-traverse rover2 waypoint4 waypoint1)
    (can-traverse rover2 waypoint2 waypoint3)
    (can-traverse rover2 waypoint3 waypoint2)
    (can-traverse rover2 waypoint2 waypoint9)
    (can-traverse rover2 waypoint9 waypoint2)
    (can-traverse rover2 waypoint2 waypoint11)
    (can-traverse rover2 waypoint11 waypoint2)
    (can-traverse rover2 waypoint6 waypoint7)
    (can-traverse rover2 waypoint7 waypoint6)
    (can-traverse rover2 waypoint6 waypoint12)
    (can-traverse rover2 waypoint12 waypoint6)
    (can-traverse rover2 waypoint8 waypoint10)
    (can-traverse rover2 waypoint10 waypoint8)
    (at rover3 waypoint13)
    (store-of rover3store rover3)
    (empty rover3store)
    (equipped-for-soil-analysis rover3)
    (equipped-for-imaging rover3)
    (can-traverse rover3 waypoint13 waypoint0)
    (can-traverse rover3 waypoint0 waypoint13)
    (can-traverse rover3 waypoint13 waypoint3)
    (can-traverse rover3 waypoint3 waypoint13)
    (can-traverse rover3 waypoint13 waypoint5)
    (can-traverse rover3 waypoint5 waypoint13)
    (can-traverse rover3 waypoint13 waypoint6)
    (can-traverse rover3 waypoint6 waypoint13)
    (can-traverse rover3 waypoint0 waypoint1)
    (can-traverse rover3 waypoint1 waypoint0)
    (can-traverse rover3 waypoint0 waypoint10)
    (can-traverse rover3 waypoint10 waypoint0)
    (can-traverse rover3 waypoint3 waypoint7)
    (can-traverse rover3 waypoint7 waypoint3)
    (can-traverse rover3 waypoint3 waypoint8)
    (can-traverse rover3 waypoint8 waypoint3)
    (can-traverse rover3 waypoint3 waypoint11)
    (can-traverse rover3 waypoint11 waypoint3)
    (can-traverse rover3 waypoint5 waypoint2)
    (can-traverse rover3 waypoint2 waypoint5)
    (can-traverse rover3 waypoint5 waypoint12)
    (can-traverse rover3 waypoint12 waypoint5)
    (can-traverse rover3 waypoint5 waypoint14)
    (can-traverse rover3 waypoint14 waypoint5)
    (can-traverse rover3 waypoint1 waypoint4)
    (can-traverse rover3 waypoint4 waypoint1)
    (at rover4 waypoint1)
    (store-of rover4store rover4)
    (empty rover4store)
    (equipped-for-rock-analysis rover4)
    (equipped-for-imaging rover4)
    (can-traverse rover4 waypoint1 waypoint0)
    (can-traverse rover4 waypoint0 waypoint1)
    (can-traverse rover4 waypoint1 waypoint4)
    (can-traverse rover4 waypoint4 waypoint1)
    (can-traverse rover4 waypoint1 waypoint5)
    (can-traverse rover4 waypoint5 waypoint1)
    (can-traverse rover4 waypoint1 waypoint8)
    (can-traverse rover4 waypoint8 waypoint1)
    (can-traverse rover4 waypoint1 waypoint12)
    (can-traverse rover4 waypoint12 waypoint1)
    (can-traverse rover4 waypoint1 waypoint14)
    (can-traverse rover4 waypoint14 waypoint1)
    (can-traverse rover4 waypoint0 waypoint3)
    (can-traverse rover4 waypoint3 waypoint0)
    (can-traverse rover4 waypoint0 waypoint6)
    (can-traverse rover4 waypoint6 waypoint0)
    (can-traverse rover4 waypoint0 waypoint10)
    (can-traverse rover4 waypoint10 waypoint0)
    (can-traverse rover4 waypoint0 waypoint13)
    (can-traverse rover4 waypoint13 waypoint0)
    (can-traverse rover4 waypoint4 waypoint2)
    (can-traverse rover4 waypoint2 waypoint4)
    (can-traverse rover4 waypoint4 waypoint11)
    (can-traverse rover4 waypoint11 waypoint4)
    (can-traverse rover4 waypoint8 waypoint7)
    (can-traverse rover4 waypoint7 waypoint8)
    (can-traverse rover4 waypoint14 waypoint9)
    (can-traverse rover4 waypoint9 waypoint14)
    (at rover5 waypoint8)
    (store-of rover5store rover5)
    (empty rover5store)
    (equipped-for-rock-analysis rover5)
    (equipped-for-imaging rover5)
    (can-traverse rover5 waypoint8 waypoint1)
    (can-traverse rover5 waypoint1 waypoint8)
    (can-traverse rover5 waypoint8 waypoint3)
    (can-traverse rover5 waypoint3 waypoint8)
    (can-traverse rover5 waypoint8 waypoint5)
    (can-traverse rover5 waypoint5 waypoint8)
    (can-traverse rover5 waypoint8 waypoint7)
    (can-traverse rover5 waypoint7 waypoint8)
    (can-traverse rover5 waypoint8 waypoint9)
    (can-traverse rover5 waypoint9 waypoint8)
    (can-traverse rover5 waypoint8 waypoint10)
    (can-traverse rover5 waypoint10 waypoint8)
    (can-traverse rover5 waypoint8 waypoint11)
    (can-traverse rover5 waypoint11 waypoint8)
    (can-traverse rover5 waypoint1 waypoint4)
    (can-traverse rover5 waypoint4 waypoint1)
    (can-traverse rover5 waypoint1 waypoint12)
    (can-traverse rover5 waypoint12 waypoint1)
    (can-traverse rover5 waypoint1 waypoint14)
    (can-traverse rover5 waypoint14 waypoint1)
    (can-traverse rover5 waypoint3 waypoint0)
    (can-traverse rover5 waypoint0 waypoint3)
    (can-traverse rover5 waypoint3 waypoint6)
    (can-traverse rover5 waypoint6 waypoint3)
    (can-traverse rover5 waypoint5 waypoint2)
    (can-traverse rover5 waypoint2 waypoint5)
    (can-traverse rover5 waypoint5 waypoint13)
    (can-traverse rover5 waypoint13 waypoint5)
    (on-board camera0 rover4)
    (calibration-target camera0 objective2)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on-board camera1 rover3)
    (calibration-target camera1 objective2)
    (supports camera1 colour)
    (on-board camera2 rover5)
    (calibration-target camera2 objective1)
    (supports camera2 colour)
    (supports camera2 high_res)
    (on-board camera3 rover3)
    (calibration-target camera3 objective5)
    (supports camera3 colour)
    (on-board camera4 rover5)
    (calibration-target camera4 objective3)
    (supports camera4 colour)
    (supports camera4 high_res)
    (supports camera4 low_res)
    (on-board camera5 rover1)
    (calibration-target camera5 objective0)
    (supports camera5 low_res)
    (on-board camera6 rover2)
    (calibration-target camera6 objective5)
    (supports camera6 colour)
    (supports camera6 high_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective0 waypoint3)
    (visible-from objective1 waypoint0)
    (visible-from objective1 waypoint1)
    (visible-from objective2 waypoint0)
    (visible-from objective2 waypoint1)
    (visible-from objective2 waypoint2)
    (visible-from objective2 waypoint3)
    (visible-from objective2 waypoint4)
    (visible-from objective2 waypoint5)
    (visible-from objective2 waypoint6)
    (visible-from objective2 waypoint7)
    (visible-from objective2 waypoint8)
    (visible-from objective2 waypoint9)
    (visible-from objective2 waypoint10)
    (visible-from objective2 waypoint11)
    (visible-from objective2 waypoint12)
    (visible-from objective2 waypoint13)
    (visible-from objective2 waypoint14)
    (visible-from objective3 waypoint0)
    (visible-from objective3 waypoint1)
    (visible-from objective3 waypoint2)
    (visible-from objective3 waypoint3)
    (visible-from objective3 waypoint4)
    (visible-from objective3 waypoint5)
    (visible-from objective4 waypoint0)
    (visible-from objective4 waypoint1)
    (visible-from objective4 waypoint2)
    (visible-from objective4 waypoint3)
    (visible-from objective4 waypoint4)
    (visible-from objective4 waypoint5)
    (visible-from objective4 waypoint6)
    (visible-from objective4 waypoint7)
    (visible-from objective4 waypoint8)
    (visible-from objective4 waypoint9)
    (visible-from objective4 waypoint10)
    (visible-from objective4 waypoint11)
    (visible-from objective4 waypoint12)
    (visible-from objective5 waypoint0)
    (visible-from objective5 waypoint1)
  )

  (:goal
    (and
      (communicated-soil-data waypoint14)
      (communicated-soil-data waypoint5)
      (communicated-soil-data waypoint2)
      (communicated-soil-data waypoint3)
      (communicated-rock-data waypoint3)
      (communicated-rock-data waypoint5)
      (communicated-rock-data waypoint12)
      (communicated-rock-data waypoint9)
      (communicated-image-data objective2 colour)
      (communicated-image-data objective2 low_res)
      (communicated-image-data objective3 colour)
      (communicated-image-data objective5 colour)
      (communicated-image-data objective4 colour)
    )
  )

  (:metric minimize (total-cost))
)
