(define (problem satellite-ipc-018-value)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 - instrument
    image1 thermograph0 thermograph2 thermograph3 thermograph4 - mode
    groundstation2 phenomenon5 phenomenon12 phenomenon13 phenomenon16 phenomenon17 phenomenon18 phenomenon21 phenomenon24 planet6 planet7 planet11 planet14 planet19 planet20 planet23 star0 star1 star3 star4 star8 star9 star10 star15 star22 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation2) 1)
    (= (target-cost phenomenon5) 2)
    (= (target-cost phenomenon12) 3)
    (= (target-cost phenomenon13) 4)
    (= (target-cost phenomenon16) 5)
    (= (target-cost phenomenon17) 6)
    (= (target-cost phenomenon18) 7)
    (= (target-cost phenomenon21) 8)
    (= (target-cost phenomenon24) 9)
    (= (target-cost planet6) 10)
    (= (target-cost planet7) 11)
    (= (target-cost planet11) 12)
    (= (target-cost planet14) 13)
    (= (target-cost planet19) 14)
    (= (target-cost planet20) 15)
    (= (target-cost planet23) 16)
    (= (target-cost star0) 17)
    (= (target-cost star1) 18)
    (= (target-cost star3) 19)
    (= (target-cost star4) 20)
    (= (target-cost star8) 21)
    (= (target-cost star9) 22)
    (= (target-cost star10) 23)
    (= (target-cost star15) 24)
    (= (target-cost star22) 25)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 2)
    (= (instrument-cost instrument2) 3)
    (= (instrument-cost instrument3) 4)
    (= (instrument-cost instrument4) 5)
    (= (instrument-cost instrument5) 6)
    (= (instrument-cost instrument6) 7)
    (= (instrument-cost instrument7) 8)
    (= (instrument-cost instrument8) 9)
    (= (instrument-cost instrument9) 10)
    (= (instrument-cost instrument10) 11)
    (= (instrument-cost instrument11) 12)
    (= (instrument-cost instrument12) 13)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 2)
    (= (satellite-move-cost satellite2) 3)
    (= (satellite-move-cost satellite3) 4)
    (= (satellite-move-cost satellite4) 5)
    (supports instrument0 thermograph4)
    (supports instrument0 thermograph0)
    (supports instrument0 thermograph2)
    (calibration-target instrument0 star4)
    (supports instrument1 thermograph3)
    (calibration-target instrument1 star0)
    (supports instrument2 image1)
    (calibration-target instrument2 star4)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star8)
    (supports instrument3 thermograph3)
    (calibration-target instrument3 star1)
    (supports instrument4 image1)
    (calibration-target instrument4 star1)
    (supports instrument5 thermograph3)
    (calibration-target instrument5 star3)
    (supports instrument6 thermograph2)
    (supports instrument6 thermograph0)
    (supports instrument6 image1)
    (calibration-target instrument6 star0)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (on-board instrument5 satellite1)
    (on-board instrument6 satellite1)
    (power-avail satellite1)
    (pointing satellite1 phenomenon21)
    (supports instrument7 thermograph0)
    (calibration-target instrument7 star3)
    (supports instrument8 thermograph4)
    (supports instrument8 thermograph3)
    (supports instrument8 thermograph2)
    (calibration-target instrument8 star3)
    (supports instrument9 thermograph2)
    (supports instrument9 thermograph3)
    (calibration-target instrument9 star1)
    (on-board instrument7 satellite2)
    (on-board instrument8 satellite2)
    (on-board instrument9 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star4)
    (supports instrument10 thermograph2)
    (calibration-target instrument10 star3)
    (supports instrument11 thermograph2)
    (supports instrument11 thermograph4)
    (supports instrument11 thermograph0)
    (calibration-target instrument11 star1)
    (on-board instrument10 satellite3)
    (on-board instrument11 satellite3)
    (power-avail satellite3)
    (pointing satellite3 phenomenon16)
    (supports instrument12 thermograph4)
    (calibration-target instrument12 star3)
    (on-board instrument12 satellite4)
    (power-avail satellite4)
    (pointing satellite4 phenomenon18)
  )

  (:goal
    (and
      (have-image phenomenon5 thermograph4)
      (have-image planet7 image1)
      (have-image star8 thermograph3)
      (have-image star9 image1)
      (have-image star10 image1)
      (have-image phenomenon13 thermograph2)
      (have-image star15 thermograph2)
      (have-image phenomenon17 thermograph4)
      (have-image phenomenon18 image1)
      (have-image planet19 thermograph2)
      (have-image planet20 thermograph4)
      (have-image phenomenon21 image1)
      (have-image star22 thermograph3)
    )
  )

  (:metric minimize (total-cost))
)
