(define (problem satellite-ipc-013-value)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 - instrument
    image3 image4 thermograph0 thermograph1 thermograph2 - mode
    groundstation2 groundstation3 phenomenon5 phenomenon12 phenomenon18 phenomenon27 planet6 planet7 planet8 planet9 planet10 planet11 planet13 planet15 planet16 planet17 planet20 planet23 planet24 planet25 planet28 planet29 star0 star1 star4 star14 star19 star21 star22 star26 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation2) 1)
    (= (target-cost groundstation3) 2)
    (= (target-cost phenomenon5) 3)
    (= (target-cost phenomenon12) 4)
    (= (target-cost phenomenon18) 5)
    (= (target-cost phenomenon27) 6)
    (= (target-cost planet6) 7)
    (= (target-cost planet7) 8)
    (= (target-cost planet8) 9)
    (= (target-cost planet9) 10)
    (= (target-cost planet10) 11)
    (= (target-cost planet11) 12)
    (= (target-cost planet13) 13)
    (= (target-cost planet15) 14)
    (= (target-cost planet16) 15)
    (= (target-cost planet17) 16)
    (= (target-cost planet20) 17)
    (= (target-cost planet23) 18)
    (= (target-cost planet24) 19)
    (= (target-cost planet25) 20)
    (= (target-cost planet28) 21)
    (= (target-cost planet29) 22)
    (= (target-cost star0) 23)
    (= (target-cost star1) 24)
    (= (target-cost star4) 25)
    (= (target-cost star14) 26)
    (= (target-cost star19) 27)
    (= (target-cost star21) 28)
    (= (target-cost star22) 29)
    (= (target-cost star26) 30)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 2)
    (= (instrument-cost instrument2) 3)
    (= (instrument-cost instrument3) 4)
    (= (instrument-cost instrument4) 5)
    (= (instrument-cost instrument5) 6)
    (= (instrument-cost instrument6) 7)
    (= (instrument-cost instrument7) 8)
    (= (instrument-cost instrument8) 9)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 2)
    (= (satellite-move-cost satellite2) 3)
    (= (satellite-move-cost satellite3) 4)
    (= (satellite-move-cost satellite4) 5)
    (supports instrument0 image4)
    (calibration-target instrument0 groundstation3)
    (supports instrument1 thermograph1)
    (supports instrument1 image4)
    (calibration-target instrument1 groundstation3)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star19)
    (supports instrument2 thermograph0)
    (supports instrument2 image4)
    (supports instrument2 thermograph2)
    (calibration-target instrument2 groundstation3)
    (on-board instrument2 satellite1)
    (power-avail satellite1)
    (pointing satellite1 planet17)
    (supports instrument3 image4)
    (supports instrument3 image3)
    (calibration-target instrument3 star1)
    (supports instrument4 image3)
    (calibration-target instrument4 groundstation3)
    (on-board instrument3 satellite2)
    (on-board instrument4 satellite2)
    (power-avail satellite2)
    (pointing satellite2 planet7)
    (supports instrument5 thermograph1)
    (supports instrument5 image4)
    (calibration-target instrument5 groundstation3)
    (on-board instrument5 satellite3)
    (power-avail satellite3)
    (pointing satellite3 star4)
    (supports instrument6 image3)
    (supports instrument6 thermograph1)
    (supports instrument6 thermograph0)
    (calibration-target instrument6 star4)
    (supports instrument7 thermograph2)
    (supports instrument7 thermograph0)
    (calibration-target instrument7 star0)
    (supports instrument8 image3)
    (supports instrument8 thermograph2)
    (calibration-target instrument8 groundstation3)
    (on-board instrument6 satellite4)
    (on-board instrument7 satellite4)
    (on-board instrument8 satellite4)
    (power-avail satellite4)
    (pointing satellite4 phenomenon5)
  )

  (:goal
    (and
      (pointing satellite1 phenomenon5)
      (pointing satellite2 planet11)
      (pointing satellite4 planet11)
      (have-image phenomenon5 thermograph1)
      (have-image planet6 image4)
      (have-image planet7 image3)
      (have-image planet8 image3)
      (have-image planet9 thermograph0)
      (have-image planet10 thermograph1)
      (have-image planet11 thermograph2)
      (have-image phenomenon12 image3)
      (have-image planet13 thermograph1)
      (have-image star14 image3)
      (have-image planet15 thermograph0)
      (have-image planet16 image3)
      (have-image planet17 image4)
      (have-image phenomenon18 image3)
      (have-image star19 thermograph0)
      (have-image star21 thermograph1)
      (have-image star22 image4)
      (have-image planet23 thermograph1)
      (have-image planet24 thermograph2)
      (have-image planet25 thermograph1)
      (have-image star26 thermograph0)
      (have-image phenomenon27 thermograph1)
      (have-image planet28 thermograph2)
      (have-image planet29 thermograph0)
    )
  )

  (:metric minimize (total-cost))
)
