(define (problem satellite-ipc-009-value)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 - instrument
    image2 image3 image4 infrared1 spectrograph0 - mode
    groundstation1 phenomenon6 phenomenon7 phenomenon8 phenomenon12 phenomenon13 planet5 planet10 planet11 star0 star2 star3 star4 star9 star14 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation1) 1)
    (= (target-cost phenomenon6) 2)
    (= (target-cost phenomenon7) 3)
    (= (target-cost phenomenon8) 4)
    (= (target-cost phenomenon12) 5)
    (= (target-cost phenomenon13) 6)
    (= (target-cost planet5) 7)
    (= (target-cost planet10) 8)
    (= (target-cost planet11) 9)
    (= (target-cost star0) 10)
    (= (target-cost star2) 11)
    (= (target-cost star3) 12)
    (= (target-cost star4) 13)
    (= (target-cost star9) 14)
    (= (target-cost star14) 15)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 2)
    (= (instrument-cost instrument2) 3)
    (= (instrument-cost instrument3) 4)
    (= (instrument-cost instrument4) 5)
    (= (instrument-cost instrument5) 6)
    (= (instrument-cost instrument6) 7)
    (= (instrument-cost instrument7) 8)
    (= (instrument-cost instrument8) 9)
    (= (instrument-cost instrument9) 10)
    (= (instrument-cost instrument10) 11)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 2)
    (= (satellite-move-cost satellite2) 3)
    (= (satellite-move-cost satellite3) 4)
    (= (satellite-move-cost satellite4) 5)
    (supports instrument0 infrared1)
    (supports instrument0 image4)
    (calibration-target instrument0 star3)
    (supports instrument1 image4)
    (supports instrument1 image2)
    (supports instrument1 spectrograph0)
    (calibration-target instrument1 star4)
    (supports instrument2 image2)
    (calibration-target instrument2 star2)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star0)
    (supports instrument3 image2)
    (supports instrument3 image3)
    (supports instrument3 image4)
    (calibration-target instrument3 star2)
    (supports instrument4 image3)
    (supports instrument4 image2)
    (calibration-target instrument4 star3)
    (supports instrument5 image4)
    (supports instrument5 infrared1)
    (supports instrument5 spectrograph0)
    (calibration-target instrument5 star3)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (on-board instrument5 satellite1)
    (power-avail satellite1)
    (pointing satellite1 planet11)
    (supports instrument6 image2)
    (supports instrument6 spectrograph0)
    (calibration-target instrument6 star2)
    (on-board instrument6 satellite2)
    (power-avail satellite2)
    (pointing satellite2 phenomenon6)
    (supports instrument7 image3)
    (supports instrument7 spectrograph0)
    (supports instrument7 image4)
    (calibration-target instrument7 star0)
    (on-board instrument7 satellite3)
    (power-avail satellite3)
    (pointing satellite3 planet10)
    (supports instrument8 image4)
    (supports instrument8 infrared1)
    (supports instrument8 image3)
    (calibration-target instrument8 groundstation1)
    (supports instrument9 image4)
    (calibration-target instrument9 star0)
    (supports instrument10 image2)
    (supports instrument10 infrared1)
    (supports instrument10 image4)
    (calibration-target instrument10 star2)
    (on-board instrument8 satellite4)
    (on-board instrument9 satellite4)
    (on-board instrument10 satellite4)
    (power-avail satellite4)
    (pointing satellite4 star9)
  )

  (:goal
    (and
      (pointing satellite0 phenomenon7)
      (pointing satellite3 star9)
      (pointing satellite4 planet5)
      (have-image planet5 image2)
      (have-image phenomenon6 image3)
      (have-image phenomenon7 infrared1)
      (have-image phenomenon8 image2)
      (have-image star9 image3)
      (have-image planet10 image4)
      (have-image planet11 spectrograph0)
      (have-image phenomenon12 image3)
      (have-image phenomenon13 spectrograph0)
      (have-image star14 image4)
    )
  )

  (:metric minimize (total-cost))
)
