(define (problem satellite-ipc-015-value)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 satellite5 satellite6 satellite7 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 - instrument
    image1 infrared0 spectrograph2 thermograph3 thermograph4 - mode
    groundstation0 groundstation2 phenomenon5 phenomenon9 phenomenon10 phenomenon16 planet6 planet7 planet11 planet14 planet17 planet20 planet21 planet22 planet23 planet24 star1 star3 star4 star8 star12 star13 star15 star18 star19 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 1)
    (= (target-cost groundstation2) 2)
    (= (target-cost phenomenon5) 3)
    (= (target-cost phenomenon9) 4)
    (= (target-cost phenomenon10) 5)
    (= (target-cost phenomenon16) 6)
    (= (target-cost planet6) 7)
    (= (target-cost planet7) 8)
    (= (target-cost planet11) 9)
    (= (target-cost planet14) 10)
    (= (target-cost planet17) 11)
    (= (target-cost planet20) 12)
    (= (target-cost planet21) 13)
    (= (target-cost planet22) 14)
    (= (target-cost planet23) 15)
    (= (target-cost planet24) 16)
    (= (target-cost star1) 17)
    (= (target-cost star3) 18)
    (= (target-cost star4) 19)
    (= (target-cost star8) 20)
    (= (target-cost star12) 21)
    (= (target-cost star13) 22)
    (= (target-cost star15) 23)
    (= (target-cost star18) 24)
    (= (target-cost star19) 25)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 2)
    (= (instrument-cost instrument2) 3)
    (= (instrument-cost instrument3) 4)
    (= (instrument-cost instrument4) 5)
    (= (instrument-cost instrument5) 6)
    (= (instrument-cost instrument6) 7)
    (= (instrument-cost instrument7) 8)
    (= (instrument-cost instrument8) 9)
    (= (instrument-cost instrument9) 10)
    (= (instrument-cost instrument10) 11)
    (= (instrument-cost instrument11) 12)
    (= (instrument-cost instrument12) 13)
    (= (instrument-cost instrument13) 14)
    (= (instrument-cost instrument14) 15)
    (= (instrument-cost instrument15) 16)
    (= (instrument-cost instrument16) 17)
    (= (instrument-cost instrument17) 18)
    (= (instrument-cost instrument18) 19)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 2)
    (= (satellite-move-cost satellite2) 3)
    (= (satellite-move-cost satellite3) 4)
    (= (satellite-move-cost satellite4) 5)
    (= (satellite-move-cost satellite5) 6)
    (= (satellite-move-cost satellite6) 7)
    (= (satellite-move-cost satellite7) 8)
    (supports instrument0 thermograph4)
    (supports instrument0 image1)
    (calibration-target instrument0 groundstation0)
    (supports instrument1 spectrograph2)
    (supports instrument1 thermograph3)
    (calibration-target instrument1 star3)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star19)
    (supports instrument2 spectrograph2)
    (calibration-target instrument2 star4)
    (supports instrument3 image1)
    (supports instrument3 spectrograph2)
    (calibration-target instrument3 groundstation2)
    (on-board instrument2 satellite1)
    (on-board instrument3 satellite1)
    (power-avail satellite1)
    (pointing satellite1 star18)
    (supports instrument4 thermograph3)
    (supports instrument4 thermograph4)
    (supports instrument4 spectrograph2)
    (calibration-target instrument4 star1)
    (supports instrument5 thermograph3)
    (supports instrument5 image1)
    (supports instrument5 infrared0)
    (calibration-target instrument5 groundstation2)
    (on-board instrument4 satellite2)
    (on-board instrument5 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star19)
    (supports instrument6 spectrograph2)
    (supports instrument6 infrared0)
    (calibration-target instrument6 groundstation2)
    (on-board instrument6 satellite3)
    (power-avail satellite3)
    (pointing satellite3 star4)
    (supports instrument7 thermograph3)
    (supports instrument7 spectrograph2)
    (calibration-target instrument7 star3)
    (supports instrument8 image1)
    (calibration-target instrument8 groundstation2)
    (supports instrument9 infrared0)
    (calibration-target instrument9 star3)
    (on-board instrument7 satellite4)
    (on-board instrument8 satellite4)
    (on-board instrument9 satellite4)
    (power-avail satellite4)
    (pointing satellite4 phenomenon9)
    (supports instrument10 thermograph4)
    (supports instrument10 spectrograph2)
    (supports instrument10 infrared0)
    (calibration-target instrument10 groundstation0)
    (supports instrument11 infrared0)
    (calibration-target instrument11 groundstation0)
    (supports instrument12 infrared0)
    (calibration-target instrument12 star1)
    (on-board instrument10 satellite5)
    (on-board instrument11 satellite5)
    (on-board instrument12 satellite5)
    (power-avail satellite5)
    (pointing satellite5 planet6)
    (supports instrument13 thermograph3)
    (supports instrument13 infrared0)
    (calibration-target instrument13 star3)
    (supports instrument14 spectrograph2)
    (calibration-target instrument14 groundstation2)
    (supports instrument15 thermograph4)
    (calibration-target instrument15 groundstation0)
    (on-board instrument13 satellite6)
    (on-board instrument14 satellite6)
    (on-board instrument15 satellite6)
    (power-avail satellite6)
    (pointing satellite6 planet17)
    (supports instrument16 thermograph4)
    (calibration-target instrument16 groundstation2)
    (supports instrument17 spectrograph2)
    (calibration-target instrument17 star1)
    (supports instrument18 thermograph4)
    (calibration-target instrument18 star4)
    (on-board instrument16 satellite7)
    (on-board instrument17 satellite7)
    (on-board instrument18 satellite7)
    (power-avail satellite7)
    (pointing satellite7 planet11)
  )

  (:goal
    (and
      (pointing satellite0 star19)
      (pointing satellite1 planet22)
      (pointing satellite2 star13)
      (pointing satellite3 planet14)
      (pointing satellite5 planet24)
      (pointing satellite7 star3)
      (have-image phenomenon5 spectrograph2)
      (have-image planet6 spectrograph2)
      (have-image planet7 infrared0)
      (have-image phenomenon9 infrared0)
      (have-image phenomenon10 image1)
      (have-image planet11 image1)
      (have-image star12 thermograph3)
      (have-image star13 thermograph3)
      (have-image planet14 thermograph4)
      (have-image star15 thermograph4)
      (have-image phenomenon16 image1)
      (have-image planet17 thermograph3)
      (have-image star18 image1)
      (have-image planet20 image1)
      (have-image planet21 infrared0)
      (have-image planet22 image1)
      (have-image planet23 thermograph3)
      (have-image planet24 infrared0)
    )
  )

  (:metric minimize (total-cost))
)
