(define (problem depots-ipc-016-value)
  (:domain depots)

  (:objects
    depot0 depot1 distributor0 distributor1 - place
    truck0 truck1 truck2 truck3 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 2)
    (= (crate-cost crate2) 3)
    (= (crate-cost crate3) 4)
    (= (crate-cost crate4) 5)
    (= (crate-cost crate5) 6)
    (= (drive-cost) 1)
    (clear crate5)
    (clear crate3)
    (clear crate4)
    (clear pallet3)
    (clear crate0)
    (clear pallet5)
    (clear pallet6)
    (clear pallet7)
    (at-truck truck0 depot1)
    (at-truck truck1 depot1)
    (at-truck truck2 depot0)
    (at-truck truck3 distributor1)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 distributor0)
    (available hoist2)
    (at-hoist hoist3 distributor1)
    (available hoist3)
    (at-hoist hoist4 distributor1)
    (available hoist4)
    (at-hoist hoist5 depot1)
    (available hoist5)
    (at-hoist hoist6 depot1)
    (available hoist6)
    (at-hoist hoist7 distributor1)
    (available hoist7)
    (at-crate crate0 depot1)
    (on crate0 pallet4)
    (at-crate crate1 depot1)
    (on crate1 pallet1)
    (at-crate crate2 depot0)
    (on crate2 pallet0)
    (at-crate crate3 depot1)
    (on crate3 crate1)
    (at-crate crate4 distributor0)
    (on crate4 pallet2)
    (at-crate crate5 depot0)
    (on crate5 crate2)
  )

  (:goal
    (and
      (on crate0 pallet3)
      (on crate2 pallet1)
      (on crate3 pallet0)
      (on crate4 crate3)
      (on crate5 pallet2)
    )
  )

  (:metric minimize (total-cost))
)
