(define (problem depots-ipc-006-value)
  (:domain depots)

  (:objects
    depot0 distributor0 distributor1 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 - hoist
    pallet0 pallet1 pallet2 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 2)
    (= (crate-cost crate2) 3)
    (= (crate-cost crate3) 4)
    (= (crate-cost crate4) 5)
    (= (crate-cost crate5) 6)
    (= (crate-cost crate6) 7)
    (= (crate-cost crate7) 8)
    (= (crate-cost crate8) 9)
    (= (crate-cost crate9) 10)
    (= (crate-cost crate10) 11)
    (= (crate-cost crate11) 12)
    (= (crate-cost crate12) 13)
    (= (crate-cost crate13) 14)
    (= (crate-cost crate14) 15)
    (= (drive-cost) 1)
    (clear crate11)
    (clear crate14)
    (clear crate10)
    (at-truck truck0 distributor1)
    (at-truck truck1 depot0)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 distributor0)
    (available hoist1)
    (at-hoist hoist2 distributor1)
    (available hoist2)
    (at-crate crate0 distributor1)
    (on crate0 pallet2)
    (at-crate crate1 depot0)
    (on crate1 pallet0)
    (at-crate crate2 distributor1)
    (on crate2 crate0)
    (at-crate crate3 distributor0)
    (on crate3 pallet1)
    (at-crate crate4 distributor0)
    (on crate4 crate3)
    (at-crate crate5 distributor1)
    (on crate5 crate2)
    (at-crate crate6 depot0)
    (on crate6 crate1)
    (at-crate crate7 distributor0)
    (on crate7 crate4)
    (at-crate crate8 distributor0)
    (on crate8 crate7)
    (at-crate crate9 distributor0)
    (on crate9 crate8)
    (at-crate crate10 distributor1)
    (on crate10 crate5)
    (at-crate crate11 depot0)
    (on crate11 crate6)
    (at-crate crate12 distributor0)
    (on crate12 crate9)
    (at-crate crate13 distributor0)
    (on crate13 crate12)
    (at-crate crate14 distributor0)
    (on crate14 crate13)
  )

  (:goal
    (and
      (on crate0 crate8)
      (on crate1 crate9)
      (on crate2 crate1)
      (on crate3 crate12)
      (on crate4 crate11)
      (on crate5 crate0)
      (on crate8 pallet0)
      (on crate9 pallet1)
      (on crate10 crate4)
      (on crate11 crate5)
      (on crate12 pallet2)
    )
  )

  (:metric minimize (total-cost))
)
