(define (problem depots-ipc-019-value)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 depot3 distributor0 distributor1 distributor2 distributor3 - place
    truck0 truck1 truck2 truck3 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 2)
    (= (crate-cost crate2) 3)
    (= (crate-cost crate3) 4)
    (= (crate-cost crate4) 5)
    (= (crate-cost crate5) 6)
    (= (crate-cost crate6) 7)
    (= (crate-cost crate7) 8)
    (= (drive-cost) 1)
    (clear crate6)
    (clear crate1)
    (clear pallet2)
    (clear crate7)
    (clear crate2)
    (clear crate5)
    (clear pallet6)
    (clear pallet7)
    (clear crate4)
    (clear crate0)
    (at-truck truck0 depot0)
    (at-truck truck1 distributor0)
    (at-truck truck2 depot2)
    (at-truck truck3 distributor3)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 depot3)
    (available hoist3)
    (at-hoist hoist4 distributor0)
    (available hoist4)
    (at-hoist hoist5 distributor1)
    (available hoist5)
    (at-hoist hoist6 distributor2)
    (available hoist6)
    (at-hoist hoist7 distributor3)
    (available hoist7)
    (at-crate crate0 depot3)
    (on crate0 pallet9)
    (at-crate crate1 depot1)
    (on crate1 pallet1)
    (at-crate crate2 distributor0)
    (on crate2 pallet4)
    (at-crate crate3 distributor1)
    (on crate3 pallet5)
    (at-crate crate4 distributor2)
    (on crate4 pallet8)
    (at-crate crate5 distributor1)
    (on crate5 crate3)
    (at-crate crate6 depot0)
    (on crate6 pallet0)
    (at-crate crate7 depot3)
    (on crate7 pallet3)
  )

  (:goal
    (and
      (on crate0 pallet6)
      (on crate1 pallet8)
      (on crate3 crate1)
      (on crate4 pallet5)
      (on crate5 crate7)
      (on crate6 pallet4)
      (on crate7 crate4)
    )
  )

  (:metric minimize (total-cost))
)
