(define (problem depots-ipc-011-value)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 distributor0 distributor1 distributor2 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 2)
    (= (crate-cost crate2) 3)
    (= (crate-cost crate3) 4)
    (= (crate-cost crate4) 5)
    (= (crate-cost crate5) 6)
    (= (crate-cost crate6) 7)
    (= (crate-cost crate7) 8)
    (= (crate-cost crate8) 9)
    (= (crate-cost crate9) 10)
    (= (drive-cost) 1)
    (clear crate1)
    (clear crate3)
    (clear crate9)
    (clear pallet3)
    (clear pallet4)
    (clear crate8)
    (at-truck truck0 depot2)
    (at-truck truck1 distributor0)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 distributor0)
    (available hoist3)
    (at-hoist hoist4 distributor1)
    (available hoist4)
    (at-hoist hoist5 distributor2)
    (available hoist5)
    (at-crate crate0 depot1)
    (on crate0 pallet1)
    (at-crate crate1 depot0)
    (on crate1 pallet0)
    (at-crate crate2 depot2)
    (on crate2 pallet2)
    (at-crate crate3 depot1)
    (on crate3 crate0)
    (at-crate crate4 depot2)
    (on crate4 crate2)
    (at-crate crate5 depot2)
    (on crate5 crate4)
    (at-crate crate6 distributor2)
    (on crate6 pallet5)
    (at-crate crate7 distributor2)
    (on crate7 crate6)
    (at-crate crate8 distributor2)
    (on crate8 crate7)
    (at-crate crate9 depot2)
    (on crate9 crate5)
  )

  (:goal
    (and
      (on crate0 crate7)
      (on crate1 pallet4)
      (on crate2 pallet5)
      (on crate3 crate9)
      (on crate4 pallet0)
      (on crate5 pallet2)
      (on crate6 crate5)
      (on crate7 crate1)
      (on crate8 pallet3)
      (on crate9 crate2)
    )
  )

  (:metric minimize (total-cost))
)
