(define (problem rovers-ipc-008-inverse)
  (:domain rovers)

  (:objects
    rover0 rover1 rover2 rover3 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
    rover0store rover1store rover2store rover3store - store
    camera0 camera1 camera2 camera3 - camera
    colour high_res low_res - mode
    objective0 objective1 objective2 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 6)
    (= (sample-cost waypoint1) 5)
    (= (sample-cost waypoint2) 4)
    (= (sample-cost waypoint3) 3)
    (= (sample-cost waypoint4) 2)
    (= (sample-cost waypoint5) 1)
    (= (image-cost objective0) 3)
    (= (image-cost objective1) 2)
    (= (image-cost objective2) 1)
    (= (rover-cost rover0) 4)
    (= (rover-cost rover1) 3)
    (= (rover-cost rover2) 2)
    (= (rover-cost rover3) 1)
    (= (communicate-cost) 1)
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint0)
    (visible waypoint1 waypoint5)
    (visible waypoint5 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint2 waypoint3)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint4)
    (visible waypoint4 waypoint2)
    (visible waypoint3 waypoint4)
    (visible waypoint4 waypoint3)
    (visible waypoint3 waypoint5)
    (visible waypoint5 waypoint3)
    (visible waypoint4 waypoint0)
    (visible waypoint0 waypoint4)
    (visible waypoint4 waypoint1)
    (visible waypoint1 waypoint4)
    (visible waypoint5 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint4)
    (visible waypoint4 waypoint5)
    (at-lander general waypoint0)
    (channel-free general)
    (at rover0 waypoint2)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-soil-analysis rover0)
    (equipped-for-rock-analysis rover0)
    (can-traverse rover0 waypoint2 waypoint0)
    (can-traverse rover0 waypoint0 waypoint2)
    (can-traverse rover0 waypoint2 waypoint3)
    (can-traverse rover0 waypoint3 waypoint2)
    (can-traverse rover0 waypoint2 waypoint4)
    (can-traverse rover0 waypoint4 waypoint2)
    (can-traverse rover0 waypoint0 waypoint1)
    (can-traverse rover0 waypoint1 waypoint0)
    (can-traverse rover0 waypoint3 waypoint5)
    (can-traverse rover0 waypoint5 waypoint3)
    (at rover1 waypoint2)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-rock-analysis rover1)
    (equipped-for-imaging rover1)
    (can-traverse rover1 waypoint2 waypoint0)
    (can-traverse rover1 waypoint0 waypoint2)
    (can-traverse rover1 waypoint2 waypoint3)
    (can-traverse rover1 waypoint3 waypoint2)
    (can-traverse rover1 waypoint2 waypoint5)
    (can-traverse rover1 waypoint5 waypoint2)
    (can-traverse rover1 waypoint0 waypoint1)
    (can-traverse rover1 waypoint1 waypoint0)
    (can-traverse rover1 waypoint3 waypoint4)
    (can-traverse rover1 waypoint4 waypoint3)
    (at rover2 waypoint2)
    (store-of rover2store rover2)
    (empty rover2store)
    (equipped-for-rock-analysis rover2)
    (equipped-for-imaging rover2)
    (can-traverse rover2 waypoint2 waypoint0)
    (can-traverse rover2 waypoint0 waypoint2)
    (can-traverse rover2 waypoint2 waypoint1)
    (can-traverse rover2 waypoint1 waypoint2)
    (can-traverse rover2 waypoint2 waypoint4)
    (can-traverse rover2 waypoint4 waypoint2)
    (can-traverse rover2 waypoint2 waypoint5)
    (can-traverse rover2 waypoint5 waypoint2)
    (can-traverse rover2 waypoint0 waypoint3)
    (can-traverse rover2 waypoint3 waypoint0)
    (at rover3 waypoint3)
    (store-of rover3store rover3)
    (empty rover3store)
    (equipped-for-soil-analysis rover3)
    (equipped-for-rock-analysis rover3)
    (equipped-for-imaging rover3)
    (can-traverse rover3 waypoint3 waypoint0)
    (can-traverse rover3 waypoint0 waypoint3)
    (can-traverse rover3 waypoint3 waypoint2)
    (can-traverse rover3 waypoint2 waypoint3)
    (can-traverse rover3 waypoint3 waypoint4)
    (can-traverse rover3 waypoint4 waypoint3)
    (can-traverse rover3 waypoint0 waypoint1)
    (can-traverse rover3 waypoint1 waypoint0)
    (can-traverse rover3 waypoint2 waypoint5)
    (can-traverse rover3 waypoint5 waypoint2)
    (on-board camera0 rover3)
    (calibration-target camera0 objective1)
    (supports camera0 colour)
    (supports camera0 high_res)
    (supports camera0 low_res)
    (on-board camera1 rover3)
    (calibration-target camera1 objective0)
    (supports camera1 colour)
    (supports camera1 high_res)
    (on-board camera2 rover1)
    (calibration-target camera2 objective0)
    (supports camera2 colour)
    (supports camera2 high_res)
    (supports camera2 low_res)
    (on-board camera3 rover2)
    (calibration-target camera3 objective1)
    (supports camera3 colour)
    (supports camera3 low_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective1 waypoint0)
    (visible-from objective2 waypoint0)
    (visible-from objective2 waypoint1)
    (visible-from objective2 waypoint2)
  )

  (:goal
    (and
      (communicated-soil-data waypoint1)
      (communicated-soil-data waypoint3)
      (communicated-soil-data waypoint4)
      (communicated-rock-data waypoint5)
      (communicated-rock-data waypoint4)
      (communicated-image-data objective0 low_res)
      (communicated-image-data objective0 high_res)
      (communicated-image-data objective2 low_res)
    )
  )

  (:metric minimize (total-cost))
)
