(define (problem rovers-ipc-012-inverse)
  (:domain rovers)

  (:objects
    rover0 rover1 rover2 rover3 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 - waypoint
    rover0store rover1store rover2store rover3store - store
    camera0 camera1 camera2 camera3 - camera
    colour high_res low_res - mode
    objective0 objective1 objective2 objective3 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 8)
    (= (sample-cost waypoint1) 7)
    (= (sample-cost waypoint2) 6)
    (= (sample-cost waypoint3) 5)
    (= (sample-cost waypoint4) 4)
    (= (sample-cost waypoint5) 3)
    (= (sample-cost waypoint6) 2)
    (= (sample-cost waypoint7) 1)
    (= (image-cost objective0) 4)
    (= (image-cost objective1) 3)
    (= (image-cost objective2) 2)
    (= (image-cost objective3) 1)
    (= (rover-cost rover0) 4)
    (= (rover-cost rover1) 3)
    (= (rover-cost rover2) 2)
    (= (rover-cost rover3) 1)
    (= (communicate-cost) 1)
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint0)
    (visible waypoint0 waypoint5)
    (visible waypoint5 waypoint0)
    (visible waypoint0 waypoint6)
    (visible waypoint6 waypoint0)
    (visible waypoint0 waypoint7)
    (visible waypoint7 waypoint0)
    (visible waypoint1 waypoint5)
    (visible waypoint5 waypoint1)
    (visible waypoint1 waypoint7)
    (visible waypoint7 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint2)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint3)
    (visible waypoint3 waypoint7)
    (visible waypoint7 waypoint3)
    (visible waypoint4 waypoint2)
    (visible waypoint2 waypoint4)
    (visible waypoint4 waypoint5)
    (visible waypoint5 waypoint4)
    (visible waypoint4 waypoint6)
    (visible waypoint6 waypoint4)
    (visible waypoint5 waypoint3)
    (visible waypoint3 waypoint5)
    (visible waypoint6 waypoint5)
    (visible waypoint5 waypoint6)
    (visible waypoint6 waypoint7)
    (visible waypoint7 waypoint6)
    (visible waypoint7 waypoint2)
    (visible waypoint2 waypoint7)
    (visible waypoint7 waypoint4)
    (visible waypoint4 waypoint7)
    (visible waypoint7 waypoint5)
    (visible waypoint5 waypoint7)
    (at-lander general waypoint2)
    (channel-free general)
    (at rover0 waypoint4)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-imaging rover0)
    (can-traverse rover0 waypoint4 waypoint2)
    (can-traverse rover0 waypoint2 waypoint4)
    (can-traverse rover0 waypoint4 waypoint5)
    (can-traverse rover0 waypoint5 waypoint4)
    (can-traverse rover0 waypoint2 waypoint3)
    (can-traverse rover0 waypoint3 waypoint2)
    (can-traverse rover0 waypoint2 waypoint7)
    (can-traverse rover0 waypoint7 waypoint2)
    (can-traverse rover0 waypoint5 waypoint0)
    (can-traverse rover0 waypoint0 waypoint5)
    (can-traverse rover0 waypoint5 waypoint1)
    (can-traverse rover0 waypoint1 waypoint5)
    (can-traverse rover0 waypoint5 waypoint6)
    (can-traverse rover0 waypoint6 waypoint5)
    (at rover1 waypoint4)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-soil-analysis rover1)
    (equipped-for-rock-analysis rover1)
    (can-traverse rover1 waypoint4 waypoint2)
    (can-traverse rover1 waypoint2 waypoint4)
    (can-traverse rover1 waypoint4 waypoint5)
    (can-traverse rover1 waypoint5 waypoint4)
    (can-traverse rover1 waypoint4 waypoint6)
    (can-traverse rover1 waypoint6 waypoint4)
    (can-traverse rover1 waypoint2 waypoint0)
    (can-traverse rover1 waypoint0 waypoint2)
    (can-traverse rover1 waypoint2 waypoint3)
    (can-traverse rover1 waypoint3 waypoint2)
    (can-traverse rover1 waypoint2 waypoint7)
    (can-traverse rover1 waypoint7 waypoint2)
    (can-traverse rover1 waypoint5 waypoint1)
    (can-traverse rover1 waypoint1 waypoint5)
    (at rover2 waypoint7)
    (store-of rover2store rover2)
    (empty rover2store)
    (equipped-for-soil-analysis rover2)
    (equipped-for-imaging rover2)
    (can-traverse rover2 waypoint7 waypoint0)
    (can-traverse rover2 waypoint0 waypoint7)
    (can-traverse rover2 waypoint7 waypoint1)
    (can-traverse rover2 waypoint1 waypoint7)
    (can-traverse rover2 waypoint7 waypoint2)
    (can-traverse rover2 waypoint2 waypoint7)
    (can-traverse rover2 waypoint7 waypoint3)
    (can-traverse rover2 waypoint3 waypoint7)
    (can-traverse rover2 waypoint7 waypoint5)
    (can-traverse rover2 waypoint5 waypoint7)
    (can-traverse rover2 waypoint7 waypoint6)
    (can-traverse rover2 waypoint6 waypoint7)
    (at rover3 waypoint7)
    (store-of rover3store rover3)
    (empty rover3store)
    (equipped-for-soil-analysis rover3)
    (equipped-for-rock-analysis rover3)
    (equipped-for-imaging rover3)
    (can-traverse rover3 waypoint7 waypoint0)
    (can-traverse rover3 waypoint0 waypoint7)
    (can-traverse rover3 waypoint7 waypoint1)
    (can-traverse rover3 waypoint1 waypoint7)
    (can-traverse rover3 waypoint7 waypoint2)
    (can-traverse rover3 waypoint2 waypoint7)
    (can-traverse rover3 waypoint7 waypoint3)
    (can-traverse rover3 waypoint3 waypoint7)
    (can-traverse rover3 waypoint7 waypoint4)
    (can-traverse rover3 waypoint4 waypoint7)
    (can-traverse rover3 waypoint7 waypoint5)
    (can-traverse rover3 waypoint5 waypoint7)
    (can-traverse rover3 waypoint0 waypoint6)
    (can-traverse rover3 waypoint6 waypoint0)
    (on-board camera0 rover3)
    (calibration-target camera0 objective2)
    (supports camera0 high_res)
    (on-board camera1 rover2)
    (calibration-target camera1 objective1)
    (supports camera1 high_res)
    (on-board camera2 rover0)
    (calibration-target camera2 objective0)
    (supports camera2 low_res)
    (on-board camera3 rover3)
    (calibration-target camera3 objective3)
    (supports camera3 colour)
    (supports camera3 high_res)
    (supports camera3 low_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective1 waypoint0)
    (visible-from objective1 waypoint1)
    (visible-from objective1 waypoint2)
    (visible-from objective1 waypoint3)
    (visible-from objective2 waypoint0)
    (visible-from objective2 waypoint1)
    (visible-from objective2 waypoint2)
    (visible-from objective2 waypoint3)
    (visible-from objective2 waypoint4)
    (visible-from objective3 waypoint0)
    (visible-from objective3 waypoint1)
    (visible-from objective3 waypoint2)
    (visible-from objective3 waypoint3)
    (visible-from objective3 waypoint4)
    (visible-from objective3 waypoint5)
  )

  (:goal
    (and
      (communicated-soil-data waypoint0)
      (communicated-rock-data waypoint3)
      (communicated-rock-data waypoint6)
      (communicated-image-data objective2 low_res)
      (communicated-image-data objective1 high_res)
      (communicated-image-data objective3 low_res)
    )
  )

  (:metric minimize (total-cost))
)
