(define (problem rovers-ipc-007-inverse)
  (:domain rovers)

  (:objects
    rover0 rover1 rover2 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
    rover0store rover1store rover2store - store
    camera0 camera1 - camera
    colour high_res low_res - mode
    objective0 objective1 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 6)
    (= (sample-cost waypoint1) 5)
    (= (sample-cost waypoint2) 4)
    (= (sample-cost waypoint3) 3)
    (= (sample-cost waypoint4) 2)
    (= (sample-cost waypoint5) 1)
    (= (image-cost objective0) 2)
    (= (image-cost objective1) 1)
    (= (rover-cost rover0) 3)
    (= (rover-cost rover1) 2)
    (= (rover-cost rover2) 1)
    (= (communicate-cost) 1)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint0)
    (visible waypoint0 waypoint5)
    (visible waypoint5 waypoint0)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint1)
    (visible waypoint1 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint2)
    (visible waypoint3 waypoint2)
    (visible waypoint2 waypoint3)
    (visible waypoint4 waypoint0)
    (visible waypoint0 waypoint4)
    (visible waypoint4 waypoint3)
    (visible waypoint3 waypoint4)
    (visible waypoint5 waypoint1)
    (visible waypoint1 waypoint5)
    (visible waypoint5 waypoint4)
    (visible waypoint4 waypoint5)
    (at-lander general waypoint3)
    (channel-free general)
    (at rover0 waypoint2)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-soil-analysis rover0)
    (equipped-for-rock-analysis rover0)
    (equipped-for-imaging rover0)
    (can-traverse rover0 waypoint2 waypoint0)
    (can-traverse rover0 waypoint0 waypoint2)
    (can-traverse rover0 waypoint2 waypoint1)
    (can-traverse rover0 waypoint1 waypoint2)
    (can-traverse rover0 waypoint2 waypoint3)
    (can-traverse rover0 waypoint3 waypoint2)
    (can-traverse rover0 waypoint2 waypoint5)
    (can-traverse rover0 waypoint5 waypoint2)
    (can-traverse rover0 waypoint0 waypoint4)
    (can-traverse rover0 waypoint4 waypoint0)
    (at rover1 waypoint3)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-rock-analysis rover1)
    (can-traverse rover1 waypoint3 waypoint0)
    (can-traverse rover1 waypoint0 waypoint3)
    (can-traverse rover1 waypoint3 waypoint2)
    (can-traverse rover1 waypoint2 waypoint3)
    (can-traverse rover1 waypoint3 waypoint4)
    (can-traverse rover1 waypoint4 waypoint3)
    (can-traverse rover1 waypoint0 waypoint1)
    (can-traverse rover1 waypoint1 waypoint0)
    (can-traverse rover1 waypoint0 waypoint5)
    (can-traverse rover1 waypoint5 waypoint0)
    (at rover2 waypoint4)
    (store-of rover2store rover2)
    (empty rover2store)
    (equipped-for-soil-analysis rover2)
    (equipped-for-rock-analysis rover2)
    (equipped-for-imaging rover2)
    (can-traverse rover2 waypoint4 waypoint0)
    (can-traverse rover2 waypoint0 waypoint4)
    (can-traverse rover2 waypoint4 waypoint5)
    (can-traverse rover2 waypoint5 waypoint4)
    (can-traverse rover2 waypoint0 waypoint1)
    (can-traverse rover2 waypoint1 waypoint0)
    (can-traverse rover2 waypoint0 waypoint3)
    (can-traverse rover2 waypoint3 waypoint0)
    (can-traverse rover2 waypoint5 waypoint2)
    (can-traverse rover2 waypoint2 waypoint5)
    (on-board camera0 rover0)
    (calibration-target camera0 objective0)
    (supports camera0 colour)
    (supports camera0 high_res)
    (on-board camera1 rover2)
    (calibration-target camera1 objective1)
    (supports camera1 high_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective0 waypoint3)
    (visible-from objective0 waypoint4)
    (visible-from objective1 waypoint0)
    (visible-from objective1 waypoint1)
    (visible-from objective1 waypoint2)
    (visible-from objective1 waypoint3)
  )

  (:goal
    (and
      (communicated-soil-data waypoint4)
      (communicated-soil-data waypoint1)
      (communicated-rock-data waypoint3)
      (communicated-rock-data waypoint2)
      (communicated-rock-data waypoint4)
      (communicated-image-data objective0 high_res)
    )
  )

  (:metric minimize (total-cost))
)
