(define (problem zenotravel-ipc-018-unit)
  (:domain zenotravel)

  (:objects
    city0 city1 city2 city3 city4 city5 city6 city7 city8 city9 city10 city11 city12 city13 city14 city15 city16 city17 - city
    plane1 plane2 plane3 plane4 plane5 - aircraft
    person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 - person
  )

  (:init
    (= (total-cost) 0)
    (= (person-cost person1) 1)
    (= (person-cost person2) 1)
    (= (person-cost person3) 1)
    (= (person-cost person4) 1)
    (= (person-cost person5) 1)
    (= (person-cost person6) 1)
    (= (person-cost person7) 1)
    (= (person-cost person8) 1)
    (= (person-cost person9) 1)
    (= (person-cost person10) 1)
    (= (person-cost person11) 1)
    (= (person-cost person12) 1)
    (= (person-cost person13) 1)
    (= (person-cost person14) 1)
    (= (person-cost person15) 1)
    (= (person-cost person16) 1)
    (= (person-cost person17) 1)
    (= (person-cost person18) 1)
    (= (person-cost person19) 1)
    (= (person-cost person20) 1)
    (= (fly-cost) 1)
    (= (zoom-cost) 1)
    (at-aircraft plane1 city11)
    (at-aircraft plane2 city12)
    (at-aircraft plane3 city12)
    (at-aircraft plane4 city14)
    (at-aircraft plane5 city14)
    (at-person person1 city7)
    (at-person person2 city16)
    (at-person person3 city9)
    (at-person person4 city6)
    (at-person person5 city6)
    (at-person person6 city0)
    (at-person person7 city6)
    (at-person person8 city8)
    (at-person person9 city13)
    (at-person person10 city14)
    (at-person person11 city7)
    (at-person person12 city15)
    (at-person person13 city4)
    (at-person person14 city14)
    (at-person person15 city10)
    (at-person person16 city5)
    (at-person person17 city10)
    (at-person person18 city11)
    (at-person person19 city9)
    (at-person person20 city3)
  )

  (:goal
    (and
      (at-aircraft plane2 city6)
      (at-person person1 city2)
      (at-person person2 city17)
      (at-person person3 city7)
      (at-person person4 city14)
      (at-person person5 city9)
      (at-person person6 city13)
      (at-person person7 city6)
      (at-person person8 city8)
      (at-person person9 city4)
      (at-person person10 city16)
      (at-person person11 city6)
      (at-person person12 city4)
      (at-person person13 city14)
      (at-person person14 city2)
      (at-person person15 city9)
      (at-person person16 city9)
      (at-person person17 city15)
      (at-person person18 city6)
      (at-person person19 city2)
      (at-person person20 city17)
    )
  )

  (:metric minimize (total-cost))
)
