(define (problem depots-ipc-018-unit)
  (:domain depots)

  (:objects
    depot0 depot1 distributor0 distributor1 - place
    truck0 truck1 truck2 truck3 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 1)
    (= (crate-cost crate2) 1)
    (= (crate-cost crate3) 1)
    (= (crate-cost crate4) 1)
    (= (crate-cost crate5) 1)
    (= (crate-cost crate6) 1)
    (= (crate-cost crate7) 1)
    (= (crate-cost crate8) 1)
    (= (crate-cost crate9) 1)
    (= (crate-cost crate10) 1)
    (= (crate-cost crate11) 1)
    (= (crate-cost crate12) 1)
    (= (crate-cost crate13) 1)
    (= (crate-cost crate14) 1)
    (= (drive-cost) 1)
    (clear crate13)
    (clear crate11)
    (clear crate14)
    (clear crate10)
    (clear pallet4)
    (clear crate8)
    (clear crate3)
    (clear crate5)
    (at-truck truck0 depot1)
    (at-truck truck1 distributor0)
    (at-truck truck2 depot0)
    (at-truck truck3 depot1)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 distributor0)
    (available hoist2)
    (at-hoist hoist3 distributor1)
    (available hoist3)
    (at-hoist hoist4 distributor0)
    (available hoist4)
    (at-hoist hoist5 depot0)
    (available hoist5)
    (at-hoist hoist6 distributor0)
    (available hoist6)
    (at-hoist hoist7 distributor1)
    (available hoist7)
    (at-crate crate0 depot0)
    (on crate0 pallet0)
    (at-crate crate1 depot1)
    (on crate1 pallet1)
    (at-crate crate2 distributor0)
    (on crate2 pallet2)
    (at-crate crate3 distributor1)
    (on crate3 pallet6)
    (at-crate crate4 depot0)
    (on crate4 crate0)
    (at-crate crate5 depot1)
    (on crate5 pallet7)
    (at-crate crate6 distributor0)
    (on crate6 pallet5)
    (at-crate crate7 depot0)
    (on crate7 crate4)
    (at-crate crate8 distributor0)
    (on crate8 crate6)
    (at-crate crate9 distributor1)
    (on crate9 pallet3)
    (at-crate crate10 distributor1)
    (on crate10 crate9)
    (at-crate crate11 depot1)
    (on crate11 crate1)
    (at-crate crate12 distributor0)
    (on crate12 crate2)
    (at-crate crate13 depot0)
    (on crate13 crate7)
    (at-crate crate14 distributor0)
    (on crate14 crate12)
  )

  (:goal
    (and
      (on crate0 crate10)
      (on crate1 pallet6)
      (on crate2 crate12)
      (on crate4 pallet4)
      (on crate5 pallet2)
      (on crate6 pallet7)
      (on crate8 crate4)
      (on crate9 crate1)
      (on crate10 pallet1)
      (on crate11 pallet5)
      (on crate12 crate5)
      (on crate13 pallet3)
      (on crate14 pallet0)
    )
  )

  (:metric minimize (total-cost))
)
