(define (problem depots-ipc-015-unit)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 distributor0 distributor1 distributor2 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 1)
    (= (crate-cost crate2) 1)
    (= (crate-cost crate3) 1)
    (= (crate-cost crate4) 1)
    (= (crate-cost crate5) 1)
    (= (crate-cost crate6) 1)
    (= (crate-cost crate7) 1)
    (= (crate-cost crate8) 1)
    (= (crate-cost crate9) 1)
    (= (crate-cost crate10) 1)
    (= (crate-cost crate11) 1)
    (= (crate-cost crate12) 1)
    (= (crate-cost crate13) 1)
    (= (crate-cost crate14) 1)
    (= (drive-cost) 1)
    (clear pallet0)
    (clear crate7)
    (clear pallet2)
    (clear crate8)
    (clear crate12)
    (clear crate11)
    (clear crate4)
    (clear crate9)
    (clear crate13)
    (clear crate14)
    (at-truck truck0 distributor1)
    (at-truck truck1 distributor2)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 distributor0)
    (available hoist3)
    (at-hoist hoist4 distributor1)
    (available hoist4)
    (at-hoist hoist5 distributor2)
    (available hoist5)
    (at-crate crate0 distributor2)
    (on crate0 pallet5)
    (at-crate crate1 distributor1)
    (on crate1 pallet4)
    (at-crate crate2 depot2)
    (on crate2 pallet8)
    (at-crate crate3 depot2)
    (on crate3 crate2)
    (at-crate crate4 depot1)
    (on crate4 pallet6)
    (at-crate crate5 distributor2)
    (on crate5 crate0)
    (at-crate crate6 depot1)
    (on crate6 pallet1)
    (at-crate crate7 depot1)
    (on crate7 crate6)
    (at-crate crate8 distributor0)
    (on crate8 pallet3)
    (at-crate crate9 distributor0)
    (on crate9 pallet7)
    (at-crate crate10 distributor1)
    (on crate10 crate1)
    (at-crate crate11 distributor2)
    (on crate11 crate5)
    (at-crate crate12 distributor1)
    (on crate12 crate10)
    (at-crate crate13 depot2)
    (on crate13 crate3)
    (at-crate crate14 distributor0)
    (on crate14 pallet9)
  )

  (:goal
    (and
      (on crate0 crate8)
      (on crate1 crate10)
      (on crate2 pallet0)
      (on crate3 pallet1)
      (on crate4 crate7)
      (on crate5 pallet5)
      (on crate6 pallet6)
      (on crate7 pallet4)
      (on crate8 pallet7)
      (on crate9 crate4)
      (on crate10 crate11)
      (on crate11 crate9)
      (on crate12 crate5)
      (on crate13 pallet8)
      (on crate14 pallet9)
    )
  )

  (:metric minimize (total-cost))
)
