(define (problem depots-ipc-008-unit)
  (:domain depots)

  (:objects
    depot0 distributor0 distributor1 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 1)
    (= (crate-cost crate2) 1)
    (= (crate-cost crate3) 1)
    (= (crate-cost crate4) 1)
    (= (crate-cost crate5) 1)
    (= (crate-cost crate6) 1)
    (= (crate-cost crate7) 1)
    (= (crate-cost crate8) 1)
    (= (crate-cost crate9) 1)
    (= (drive-cost) 1)
    (clear crate2)
    (clear crate6)
    (clear crate9)
    (clear crate7)
    (clear crate0)
    (clear crate8)
    (at-truck truck0 distributor0)
    (at-truck truck1 distributor0)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 distributor0)
    (available hoist1)
    (at-hoist hoist2 distributor1)
    (available hoist2)
    (at-crate crate0 distributor0)
    (on crate0 pallet4)
    (at-crate crate1 distributor0)
    (on crate1 pallet1)
    (at-crate crate2 depot0)
    (on crate2 pallet0)
    (at-crate crate3 distributor0)
    (on crate3 pallet5)
    (at-crate crate4 distributor1)
    (on crate4 pallet3)
    (at-crate crate5 distributor0)
    (on crate5 crate1)
    (at-crate crate6 distributor0)
    (on crate6 crate5)
    (at-crate crate7 distributor1)
    (on crate7 crate4)
    (at-crate crate8 distributor0)
    (on crate8 crate3)
    (at-crate crate9 distributor1)
    (on crate9 pallet2)
  )

  (:goal
    (and
      (on crate0 pallet3)
      (on crate1 crate0)
      (on crate3 crate8)
      (on crate6 pallet2)
      (on crate7 pallet1)
      (on crate8 pallet4)
      (on crate9 pallet0)
    )
  )

  (:metric minimize (total-cost))
)
