(define (problem depots-ipc-014-unit)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 distributor0 distributor1 distributor2 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 1)
    (= (crate-cost crate2) 1)
    (= (crate-cost crate3) 1)
    (= (crate-cost crate4) 1)
    (= (crate-cost crate5) 1)
    (= (crate-cost crate6) 1)
    (= (crate-cost crate7) 1)
    (= (crate-cost crate8) 1)
    (= (crate-cost crate9) 1)
    (= (drive-cost) 1)
    (clear crate4)
    (clear crate8)
    (clear pallet2)
    (clear crate9)
    (clear crate7)
    (clear pallet5)
    (clear crate3)
    (clear pallet7)
    (clear crate0)
    (clear crate5)
    (at-truck truck0 depot1)
    (at-truck truck1 depot2)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 distributor0)
    (available hoist3)
    (at-hoist hoist4 distributor1)
    (available hoist4)
    (at-hoist hoist5 distributor2)
    (available hoist5)
    (at-crate crate0 distributor1)
    (on crate0 pallet8)
    (at-crate crate1 depot0)
    (on crate1 pallet9)
    (at-crate crate2 distributor0)
    (on crate2 pallet3)
    (at-crate crate3 distributor2)
    (on crate3 pallet6)
    (at-crate crate4 depot0)
    (on crate4 pallet0)
    (at-crate crate5 depot0)
    (on crate5 crate1)
    (at-crate crate6 distributor1)
    (on crate6 pallet4)
    (at-crate crate7 distributor1)
    (on crate7 crate6)
    (at-crate crate8 depot1)
    (on crate8 pallet1)
    (at-crate crate9 distributor0)
    (on crate9 crate2)
  )

  (:goal
    (and
      (on crate1 pallet8)
      (on crate2 pallet3)
      (on crate4 pallet0)
      (on crate5 pallet5)
      (on crate6 pallet1)
      (on crate7 crate6)
      (on crate9 crate7)
    )
  )

  (:metric minimize (total-cost))
)
