(define (problem zenotravel-ipc-015-heavy)
  (:domain zenotravel)

  (:objects
    city0 city1 city2 city3 city4 city5 city6 city7 city8 city9 city10 city11 - city
    plane1 plane2 plane3 plane4 plane5 - aircraft
    person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 - person
  )

  (:init
    (= (total-cost) 0)
    (= (person-cost person1) 1)
    (= (person-cost person2) 1)
    (= (person-cost person3) 1)
    (= (person-cost person4) 1)
    (= (person-cost person5) 1)
    (= (person-cost person6) 1)
    (= (person-cost person7) 1)
    (= (person-cost person8) 1)
    (= (person-cost person9) 1)
    (= (person-cost person10) 1)
    (= (person-cost person11) 1)
    (= (person-cost person12) 10)
    (= (person-cost person13) 10)
    (= (person-cost person14) 10)
    (= (person-cost person15) 10)
    (= (fly-cost) 1)
    (= (zoom-cost) 1)
    (at-aircraft plane1 city0)
    (at-aircraft plane2 city3)
    (at-aircraft plane3 city2)
    (at-aircraft plane4 city9)
    (at-aircraft plane5 city5)
    (at-person person1 city8)
    (at-person person2 city10)
    (at-person person3 city7)
    (at-person person4 city5)
    (at-person person5 city1)
    (at-person person6 city10)
    (at-person person7 city11)
    (at-person person8 city8)
    (at-person person9 city9)
    (at-person person10 city11)
    (at-person person11 city4)
    (at-person person12 city5)
    (at-person person13 city8)
    (at-person person14 city4)
    (at-person person15 city1)
  )

  (:goal
    (and
      (at-person person1 city1)
      (at-person person2 city4)
      (at-person person3 city7)
      (at-person person4 city6)
      (at-person person5 city8)
      (at-person person6 city11)
      (at-person person7 city2)
      (at-person person8 city11)
      (at-person person10 city9)
      (at-person person11 city6)
      (at-person person12 city4)
      (at-person person13 city11)
      (at-person person14 city4)
      (at-person person15 city6)
    )
  )

  (:metric minimize (total-cost))
)
