(define (problem gripper-074-value)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 ball16 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 1)
    (= (ball-cost ball2) 2)
    (= (ball-cost ball3) 3)
    (= (ball-cost ball4) 4)
    (= (ball-cost ball5) 5)
    (= (ball-cost ball6) 6)
    (= (ball-cost ball7) 7)
    (= (ball-cost ball8) 8)
    (= (ball-cost ball9) 9)
    (= (ball-cost ball10) 10)
    (= (ball-cost ball11) 11)
    (= (ball-cost ball12) 12)
    (= (ball-cost ball13) 13)
    (= (ball-cost ball14) 14)
    (= (ball-cost ball15) 15)
    (= (ball-cost ball16) 16)
    (at-robby room0)
    (free left)
    (free right)
    (at ball1 room2)
    (at ball2 room0)
    (at ball3 room0)
    (at ball4 room1)
    (at ball5 room2)
    (at ball6 room3)
    (at ball7 room3)
    (at ball8 room3)
    (at ball9 room1)
    (at ball10 room3)
    (at ball11 room0)
    (at ball12 room3)
    (at ball13 room2)
    (at ball14 room2)
    (at ball15 room0)
    (at ball16 room2)
  )

  (:goal
    (and
      (at ball1 room1)
      (at ball2 room2)
      (at ball3 room1)
      (at ball4 room3)
      (at ball5 room3)
      (at ball6 room0)
      (at ball7 room0)
      (at ball8 room1)
      (at ball9 room2)
      (at ball10 room0)
      (at ball11 room2)
      (at ball12 room1)
      (at ball13 room1)
      (at ball14 room1)
      (at ball15 room2)
      (at ball16 room0)
    )
  )

  (:metric minimize (total-cost))
)
