(define (problem zenotravel-ipc-017-value)
  (:domain zenotravel)

  (:objects
    city0 city1 city2 city3 city4 city5 city6 city7 city8 city9 city10 city11 city12 city13 city14 city15 - city
    plane1 plane2 plane3 plane4 plane5 - aircraft
    person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 - person
  )

  (:init
    (= (total-cost) 0)
    (= (person-cost person1) 1)
    (= (person-cost person2) 2)
    (= (person-cost person3) 3)
    (= (person-cost person4) 4)
    (= (person-cost person5) 5)
    (= (person-cost person6) 6)
    (= (person-cost person7) 7)
    (= (person-cost person8) 8)
    (= (person-cost person9) 9)
    (= (person-cost person10) 10)
    (= (person-cost person11) 11)
    (= (person-cost person12) 12)
    (= (person-cost person13) 13)
    (= (person-cost person14) 14)
    (= (person-cost person15) 15)
    (= (person-cost person16) 16)
    (= (person-cost person17) 17)
    (= (person-cost person18) 18)
    (= (person-cost person19) 19)
    (= (person-cost person20) 20)
    (= (fly-cost) 1)
    (= (zoom-cost) 1)
    (at-aircraft plane1 city14)
    (at-aircraft plane2 city11)
    (at-aircraft plane3 city4)
    (at-aircraft plane4 city11)
    (at-aircraft plane5 city15)
    (at-person person1 city0)
    (at-person person2 city14)
    (at-person person3 city12)
    (at-person person4 city7)
    (at-person person5 city4)
    (at-person person6 city14)
    (at-person person7 city4)
    (at-person person8 city0)
    (at-person person9 city3)
    (at-person person10 city7)
    (at-person person11 city3)
    (at-person person12 city15)
    (at-person person13 city10)
    (at-person person14 city1)
    (at-person person15 city7)
    (at-person person16 city9)
    (at-person person17 city7)
    (at-person person18 city5)
    (at-person person19 city11)
    (at-person person20 city0)
  )

  (:goal
    (and
      (at-aircraft plane1 city14)
      (at-aircraft plane3 city7)
      (at-aircraft plane5 city12)
      (at-person person1 city4)
      (at-person person2 city11)
      (at-person person3 city0)
      (at-person person4 city12)
      (at-person person5 city12)
      (at-person person6 city0)
      (at-person person7 city5)
      (at-person person8 city13)
      (at-person person9 city9)
      (at-person person10 city7)
      (at-person person11 city7)
      (at-person person12 city6)
      (at-person person13 city2)
      (at-person person14 city10)
      (at-person person15 city14)
      (at-person person16 city12)
      (at-person person17 city1)
      (at-person person18 city1)
      (at-person person19 city5)
      (at-person person20 city13)
    )
  )

  (:metric minimize (total-cost))
)
