(define (problem depots-ipc-009-inverse)
  (:domain depots)

  (:objects
    depot0 distributor0 distributor1 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 15)
    (= (crate-cost crate1) 14)
    (= (crate-cost crate2) 13)
    (= (crate-cost crate3) 12)
    (= (crate-cost crate4) 11)
    (= (crate-cost crate5) 10)
    (= (crate-cost crate6) 9)
    (= (crate-cost crate7) 8)
    (= (crate-cost crate8) 7)
    (= (crate-cost crate9) 6)
    (= (crate-cost crate10) 5)
    (= (crate-cost crate11) 4)
    (= (crate-cost crate12) 3)
    (= (crate-cost crate13) 2)
    (= (crate-cost crate14) 1)
    (= (drive-cost) 1)
    (clear crate2)
    (clear crate14)
    (clear crate13)
    (clear crate10)
    (clear crate12)
    (clear crate8)
    (at-truck truck0 distributor0)
    (at-truck truck1 distributor0)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 distributor0)
    (available hoist1)
    (at-hoist hoist2 distributor1)
    (available hoist2)
    (at-crate crate0 distributor1)
    (on crate0 pallet2)
    (at-crate crate1 depot0)
    (on crate1 pallet0)
    (at-crate crate2 depot0)
    (on crate2 crate1)
    (at-crate crate3 distributor0)
    (on crate3 pallet1)
    (at-crate crate4 distributor1)
    (on crate4 crate0)
    (at-crate crate5 distributor1)
    (on crate5 pallet3)
    (at-crate crate6 distributor0)
    (on crate6 crate3)
    (at-crate crate7 distributor0)
    (on crate7 crate6)
    (at-crate crate8 depot0)
    (on crate8 pallet5)
    (at-crate crate9 distributor0)
    (on crate9 crate7)
    (at-crate crate10 distributor1)
    (on crate10 crate5)
    (at-crate crate11 distributor0)
    (on crate11 pallet4)
    (at-crate crate12 distributor0)
    (on crate12 crate11)
    (at-crate crate13 distributor1)
    (on crate13 crate4)
    (at-crate crate14 distributor0)
    (on crate14 crate9)
  )

  (:goal
    (and
      (on crate0 crate5)
      (on crate1 crate2)
      (on crate2 crate10)
      (on crate3 pallet0)
      (on crate4 crate6)
      (on crate5 pallet5)
      (on crate6 pallet4)
      (on crate9 crate1)
      (on crate10 pallet2)
      (on crate11 pallet1)
      (on crate12 crate14)
      (on crate13 crate3)
      (on crate14 pallet3)
    )
  )

  (:metric minimize (total-cost))
)
