(define (problem depots-ipc-013-inverse)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 distributor0 distributor1 distributor2 - place
    truck0 truck1 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 6)
    (= (crate-cost crate1) 5)
    (= (crate-cost crate2) 4)
    (= (crate-cost crate3) 3)
    (= (crate-cost crate4) 2)
    (= (crate-cost crate5) 1)
    (= (drive-cost) 1)
    (clear crate2)
    (clear pallet1)
    (clear crate5)
    (clear crate4)
    (clear pallet4)
    (clear pallet5)
    (clear pallet6)
    (clear pallet7)
    (clear crate3)
    (clear pallet9)
    (at-truck truck0 distributor1)
    (at-truck truck1 depot0)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 distributor0)
    (available hoist3)
    (at-hoist hoist4 distributor1)
    (available hoist4)
    (at-hoist hoist5 distributor2)
    (available hoist5)
    (at-crate crate0 depot2)
    (on crate0 pallet2)
    (at-crate crate1 depot2)
    (on crate1 crate0)
    (at-crate crate2 depot0)
    (on crate2 pallet0)
    (at-crate crate3 depot0)
    (on crate3 pallet8)
    (at-crate crate4 distributor0)
    (on crate4 pallet3)
    (at-crate crate5 depot2)
    (on crate5 crate1)
  )

  (:goal
    (and
      (on crate0 pallet0)
      (on crate1 pallet5)
      (on crate2 pallet4)
      (on crate3 pallet7)
      (on crate4 pallet9)
      (on crate5 pallet1)
    )
  )

  (:metric minimize (total-cost))
)
