(define (problem depots-ipc-020-inverse)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 depot3 distributor0 distributor1 distributor2 distributor3 - place
    truck0 truck1 truck2 truck3 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 15)
    (= (crate-cost crate1) 14)
    (= (crate-cost crate2) 13)
    (= (crate-cost crate3) 12)
    (= (crate-cost crate4) 11)
    (= (crate-cost crate5) 10)
    (= (crate-cost crate6) 9)
    (= (crate-cost crate7) 8)
    (= (crate-cost crate8) 7)
    (= (crate-cost crate9) 6)
    (= (crate-cost crate10) 5)
    (= (crate-cost crate11) 4)
    (= (crate-cost crate12) 3)
    (= (crate-cost crate13) 2)
    (= (crate-cost crate14) 1)
    (= (drive-cost) 1)
    (clear crate13)
    (clear crate14)
    (clear pallet2)
    (clear crate5)
    (clear pallet4)
    (clear crate9)
    (clear crate8)
    (clear crate10)
    (clear crate11)
    (clear pallet9)
    (at-truck truck0 distributor2)
    (at-truck truck1 depot0)
    (at-truck truck2 depot1)
    (at-truck truck3 distributor1)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 depot3)
    (available hoist3)
    (at-hoist hoist4 distributor0)
    (available hoist4)
    (at-hoist hoist5 distributor1)
    (available hoist5)
    (at-hoist hoist6 distributor2)
    (available hoist6)
    (at-hoist hoist7 distributor3)
    (available hoist7)
    (at-crate crate0 distributor3)
    (on crate0 pallet7)
    (at-crate crate1 distributor1)
    (on crate1 pallet5)
    (at-crate crate2 depot3)
    (on crate2 pallet3)
    (at-crate crate3 depot0)
    (on crate3 pallet0)
    (at-crate crate4 depot0)
    (on crate4 crate3)
    (at-crate crate5 depot3)
    (on crate5 crate2)
    (at-crate crate6 depot1)
    (on crate6 pallet1)
    (at-crate crate7 distributor2)
    (on crate7 pallet6)
    (at-crate crate8 distributor2)
    (on crate8 crate7)
    (at-crate crate9 distributor1)
    (on crate9 crate1)
    (at-crate crate10 distributor3)
    (on crate10 crate0)
    (at-crate crate11 depot1)
    (on crate11 pallet8)
    (at-crate crate12 depot1)
    (on crate12 crate6)
    (at-crate crate13 depot0)
    (on crate13 crate4)
    (at-crate crate14 depot1)
    (on crate14 crate12)
  )

  (:goal
    (and
      (on crate0 pallet3)
      (on crate1 crate11)
      (on crate2 pallet6)
      (on crate3 crate0)
      (on crate4 crate5)
      (on crate5 crate14)
      (on crate6 pallet4)
      (on crate7 pallet2)
      (on crate8 pallet7)
      (on crate9 crate8)
      (on crate11 pallet5)
      (on crate12 crate6)
      (on crate13 crate2)
      (on crate14 pallet1)
    )
  )

  (:metric minimize (total-cost))
)
