(define (problem satellite-ipc-010-heavy)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 - instrument
    image2 image4 infrared0 infrared3 spectrograph1 - mode
    groundstation3 phenomenon8 phenomenon13 phenomenon14 planet5 planet9 planet10 star0 star1 star2 star4 star6 star7 star11 star12 star15 star16 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation3) 1)
    (= (target-cost phenomenon8) 1)
    (= (target-cost phenomenon13) 1)
    (= (target-cost phenomenon14) 1)
    (= (target-cost planet5) 1)
    (= (target-cost planet9) 1)
    (= (target-cost planet10) 1)
    (= (target-cost star0) 1)
    (= (target-cost star1) 1)
    (= (target-cost star2) 1)
    (= (target-cost star4) 1)
    (= (target-cost star6) 1)
    (= (target-cost star7) 10)
    (= (target-cost star11) 10)
    (= (target-cost star12) 10)
    (= (target-cost star15) 10)
    (= (target-cost star16) 10)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 10)
    (= (instrument-cost instrument9) 10)
    (= (instrument-cost instrument10) 10)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 10)
    (= (satellite-move-cost satellite4) 10)
    (supports instrument0 image4)
    (calibration-target instrument0 star1)
    (supports instrument1 infrared0)
    (supports instrument1 spectrograph1)
    (calibration-target instrument1 groundstation3)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star0)
    (supports instrument2 infrared0)
    (supports instrument2 image2)
    (calibration-target instrument2 groundstation3)
    (supports instrument3 infrared3)
    (supports instrument3 infrared0)
    (calibration-target instrument3 star4)
    (on-board instrument2 satellite1)
    (on-board instrument3 satellite1)
    (power-avail satellite1)
    (pointing satellite1 star4)
    (supports instrument4 spectrograph1)
    (supports instrument4 image4)
    (supports instrument4 infrared0)
    (calibration-target instrument4 star2)
    (supports instrument5 image2)
    (supports instrument5 infrared0)
    (supports instrument5 infrared3)
    (calibration-target instrument5 star0)
    (on-board instrument4 satellite2)
    (on-board instrument5 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star1)
    (supports instrument6 infrared0)
    (supports instrument6 infrared3)
    (calibration-target instrument6 groundstation3)
    (supports instrument7 image4)
    (supports instrument7 spectrograph1)
    (supports instrument7 infrared3)
    (calibration-target instrument7 star4)
    (on-board instrument6 satellite3)
    (on-board instrument7 satellite3)
    (power-avail satellite3)
    (pointing satellite3 groundstation3)
    (supports instrument8 spectrograph1)
    (supports instrument8 image4)
    (calibration-target instrument8 star4)
    (supports instrument9 infrared3)
    (calibration-target instrument9 star2)
    (supports instrument10 image2)
    (supports instrument10 image4)
    (calibration-target instrument10 star0)
    (on-board instrument8 satellite4)
    (on-board instrument9 satellite4)
    (on-board instrument10 satellite4)
    (power-avail satellite4)
    (pointing satellite4 planet10)
  )

  (:goal
    (and
      (pointing satellite4 planet9)
      (have-image planet5 image4)
      (have-image star6 infrared3)
      (have-image star7 image4)
      (have-image phenomenon8 image4)
      (have-image planet9 infrared0)
      (have-image planet10 infrared3)
      (have-image star12 image4)
      (have-image phenomenon13 image4)
      (have-image phenomenon14 spectrograph1)
      (have-image star15 spectrograph1)
      (have-image star16 image2)
    )
  )

  (:metric minimize (total-cost))
)
