(define (problem satellite-ipc-016-heavy)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 satellite5 satellite6 satellite7 satellite8 satellite9 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 - instrument
    image0 image2 infrared4 spectrograph3 thermograph1 - mode
    groundstation0 groundstation1 groundstation4 phenomenon5 phenomenon9 phenomenon17 phenomenon18 phenomenon23 planet6 planet7 planet8 planet10 planet11 planet19 planet21 planet22 star2 star3 star12 star13 star14 star15 star16 star20 star24 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 1)
    (= (target-cost groundstation1) 1)
    (= (target-cost groundstation4) 1)
    (= (target-cost phenomenon5) 1)
    (= (target-cost phenomenon9) 1)
    (= (target-cost phenomenon17) 1)
    (= (target-cost phenomenon18) 1)
    (= (target-cost phenomenon23) 1)
    (= (target-cost planet6) 1)
    (= (target-cost planet7) 1)
    (= (target-cost planet8) 1)
    (= (target-cost planet10) 1)
    (= (target-cost planet11) 1)
    (= (target-cost planet19) 1)
    (= (target-cost planet21) 1)
    (= (target-cost planet22) 1)
    (= (target-cost star2) 1)
    (= (target-cost star3) 1)
    (= (target-cost star12) 10)
    (= (target-cost star13) 10)
    (= (target-cost star14) 10)
    (= (target-cost star15) 10)
    (= (target-cost star16) 10)
    (= (target-cost star20) 10)
    (= (target-cost star24) 10)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (instrument-cost instrument9) 1)
    (= (instrument-cost instrument10) 1)
    (= (instrument-cost instrument11) 1)
    (= (instrument-cost instrument12) 1)
    (= (instrument-cost instrument13) 1)
    (= (instrument-cost instrument14) 1)
    (= (instrument-cost instrument15) 1)
    (= (instrument-cost instrument16) 1)
    (= (instrument-cost instrument17) 10)
    (= (instrument-cost instrument18) 10)
    (= (instrument-cost instrument19) 10)
    (= (instrument-cost instrument20) 10)
    (= (instrument-cost instrument21) 10)
    (= (instrument-cost instrument22) 10)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 1)
    (= (satellite-move-cost satellite4) 1)
    (= (satellite-move-cost satellite5) 1)
    (= (satellite-move-cost satellite6) 1)
    (= (satellite-move-cost satellite7) 10)
    (= (satellite-move-cost satellite8) 10)
    (= (satellite-move-cost satellite9) 10)
    (supports instrument0 infrared4)
    (calibration-target instrument0 star3)
    (supports instrument1 spectrograph3)
    (calibration-target instrument1 groundstation0)
    (supports instrument2 image0)
    (supports instrument2 thermograph1)
    (supports instrument2 image2)
    (calibration-target instrument2 groundstation1)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star15)
    (supports instrument3 thermograph1)
    (supports instrument3 image0)
    (calibration-target instrument3 groundstation4)
    (supports instrument4 image2)
    (supports instrument4 thermograph1)
    (calibration-target instrument4 star3)
    (supports instrument5 spectrograph3)
    (supports instrument5 thermograph1)
    (supports instrument5 image2)
    (calibration-target instrument5 groundstation4)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (on-board instrument5 satellite1)
    (power-avail satellite1)
    (pointing satellite1 planet10)
    (supports instrument6 image0)
    (calibration-target instrument6 groundstation1)
    (on-board instrument6 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star24)
    (supports instrument7 infrared4)
    (calibration-target instrument7 star3)
    (on-board instrument7 satellite3)
    (power-avail satellite3)
    (pointing satellite3 phenomenon9)
    (supports instrument8 spectrograph3)
    (calibration-target instrument8 groundstation0)
    (supports instrument9 image0)
    (supports instrument9 image2)
    (supports instrument9 thermograph1)
    (calibration-target instrument9 star3)
    (supports instrument10 image0)
    (supports instrument10 image2)
    (supports instrument10 spectrograph3)
    (calibration-target instrument10 star2)
    (on-board instrument8 satellite4)
    (on-board instrument9 satellite4)
    (on-board instrument10 satellite4)
    (power-avail satellite4)
    (pointing satellite4 planet19)
    (supports instrument11 image0)
    (calibration-target instrument11 star3)
    (supports instrument12 infrared4)
    (supports instrument12 image0)
    (calibration-target instrument12 groundstation4)
    (supports instrument13 spectrograph3)
    (calibration-target instrument13 star2)
    (on-board instrument11 satellite5)
    (on-board instrument12 satellite5)
    (on-board instrument13 satellite5)
    (power-avail satellite5)
    (pointing satellite5 planet10)
    (supports instrument14 spectrograph3)
    (supports instrument14 thermograph1)
    (supports instrument14 image0)
    (calibration-target instrument14 star3)
    (supports instrument15 image0)
    (supports instrument15 thermograph1)
    (supports instrument15 image2)
    (calibration-target instrument15 groundstation4)
    (supports instrument16 spectrograph3)
    (supports instrument16 image2)
    (calibration-target instrument16 groundstation0)
    (on-board instrument14 satellite6)
    (on-board instrument15 satellite6)
    (on-board instrument16 satellite6)
    (power-avail satellite6)
    (pointing satellite6 planet11)
    (supports instrument17 thermograph1)
    (supports instrument17 image2)
    (supports instrument17 image0)
    (calibration-target instrument17 groundstation4)
    (supports instrument18 image2)
    (supports instrument18 thermograph1)
    (calibration-target instrument18 star3)
    (on-board instrument17 satellite7)
    (on-board instrument18 satellite7)
    (power-avail satellite7)
    (pointing satellite7 planet11)
    (supports instrument19 thermograph1)
    (supports instrument19 infrared4)
    (calibration-target instrument19 star2)
    (supports instrument20 thermograph1)
    (calibration-target instrument20 groundstation4)
    (supports instrument21 thermograph1)
    (calibration-target instrument21 star2)
    (on-board instrument19 satellite8)
    (on-board instrument20 satellite8)
    (on-board instrument21 satellite8)
    (power-avail satellite8)
    (pointing satellite8 groundstation4)
    (supports instrument22 spectrograph3)
    (supports instrument22 thermograph1)
    (supports instrument22 infrared4)
    (calibration-target instrument22 groundstation1)
    (on-board instrument22 satellite9)
    (power-avail satellite9)
    (pointing satellite9 planet11)
  )

  (:goal
    (and
      (pointing satellite5 planet6)
      (pointing satellite7 star3)
      (pointing satellite8 star15)
      (pointing satellite9 star16)
      (have-image phenomenon5 thermograph1)
      (have-image planet6 infrared4)
      (have-image planet7 image0)
      (have-image planet8 thermograph1)
      (have-image phenomenon9 image2)
      (have-image planet10 image0)
      (have-image planet11 infrared4)
      (have-image star12 image0)
      (have-image star13 image0)
      (have-image star14 thermograph1)
      (have-image star15 image0)
      (have-image star16 thermograph1)
      (have-image phenomenon17 infrared4)
      (have-image phenomenon18 spectrograph3)
      (have-image star20 image0)
      (have-image planet21 thermograph1)
      (have-image planet22 image2)
      (have-image phenomenon23 image0)
      (have-image star24 infrared4)
    )
  )

  (:metric minimize (total-cost))
)
