(define (problem satellite-ipc-014-heavy)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 satellite5 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 - instrument
    image1 image2 thermograph0 thermograph3 thermograph4 - mode
    groundstation0 groundstation1 groundstation2 groundstation3 groundstation4 phenomenon5 phenomenon6 phenomenon7 phenomenon11 phenomenon12 phenomenon13 phenomenon18 planet8 planet15 planet16 planet17 planet21 planet23 star9 star10 star14 star19 star20 star22 star24 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 1)
    (= (target-cost groundstation1) 1)
    (= (target-cost groundstation2) 1)
    (= (target-cost groundstation3) 1)
    (= (target-cost groundstation4) 1)
    (= (target-cost phenomenon5) 1)
    (= (target-cost phenomenon6) 1)
    (= (target-cost phenomenon7) 1)
    (= (target-cost phenomenon11) 1)
    (= (target-cost phenomenon12) 1)
    (= (target-cost phenomenon13) 1)
    (= (target-cost phenomenon18) 1)
    (= (target-cost planet8) 1)
    (= (target-cost planet15) 1)
    (= (target-cost planet16) 1)
    (= (target-cost planet17) 1)
    (= (target-cost planet21) 1)
    (= (target-cost planet23) 1)
    (= (target-cost star9) 10)
    (= (target-cost star10) 10)
    (= (target-cost star14) 10)
    (= (target-cost star19) 10)
    (= (target-cost star20) 10)
    (= (target-cost star22) 10)
    (= (target-cost star24) 10)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (instrument-cost instrument9) 10)
    (= (instrument-cost instrument10) 10)
    (= (instrument-cost instrument11) 10)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 1)
    (= (satellite-move-cost satellite4) 10)
    (= (satellite-move-cost satellite5) 10)
    (supports instrument0 thermograph0)
    (supports instrument0 image1)
    (calibration-target instrument0 groundstation2)
    (supports instrument1 image2)
    (supports instrument1 thermograph3)
    (calibration-target instrument1 groundstation0)
    (supports instrument2 image1)
    (supports instrument2 thermograph3)
    (supports instrument2 thermograph4)
    (calibration-target instrument2 groundstation2)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 phenomenon12)
    (supports instrument3 thermograph0)
    (supports instrument3 thermograph4)
    (supports instrument3 image2)
    (calibration-target instrument3 groundstation2)
    (on-board instrument3 satellite1)
    (power-avail satellite1)
    (pointing satellite1 groundstation1)
    (supports instrument4 thermograph4)
    (supports instrument4 image1)
    (supports instrument4 thermograph0)
    (calibration-target instrument4 groundstation1)
    (supports instrument5 thermograph4)
    (calibration-target instrument5 groundstation4)
    (supports instrument6 thermograph3)
    (supports instrument6 image1)
    (calibration-target instrument6 groundstation0)
    (on-board instrument4 satellite2)
    (on-board instrument5 satellite2)
    (on-board instrument6 satellite2)
    (power-avail satellite2)
    (pointing satellite2 groundstation2)
    (supports instrument7 image2)
    (supports instrument7 thermograph3)
    (calibration-target instrument7 groundstation4)
    (supports instrument8 thermograph4)
    (supports instrument8 thermograph0)
    (calibration-target instrument8 groundstation2)
    (on-board instrument7 satellite3)
    (on-board instrument8 satellite3)
    (power-avail satellite3)
    (pointing satellite3 groundstation4)
    (supports instrument9 thermograph0)
    (supports instrument9 image2)
    (supports instrument9 image1)
    (calibration-target instrument9 groundstation2)
    (supports instrument10 thermograph3)
    (supports instrument10 image1)
    (calibration-target instrument10 groundstation0)
    (on-board instrument9 satellite4)
    (on-board instrument10 satellite4)
    (power-avail satellite4)
    (pointing satellite4 planet15)
    (supports instrument11 thermograph0)
    (supports instrument11 image2)
    (calibration-target instrument11 groundstation1)
    (on-board instrument11 satellite5)
    (power-avail satellite5)
    (pointing satellite5 phenomenon11)
  )

  (:goal
    (and
      (pointing satellite0 planet21)
      (pointing satellite2 star14)
      (pointing satellite5 planet17)
      (have-image phenomenon5 image1)
      (have-image phenomenon7 thermograph0)
      (have-image planet8 image2)
      (have-image star9 thermograph0)
      (have-image star10 thermograph3)
      (have-image phenomenon12 thermograph0)
      (have-image phenomenon13 image1)
      (have-image star14 thermograph4)
      (have-image planet15 image2)
      (have-image planet17 image2)
      (have-image phenomenon18 image1)
      (have-image star19 thermograph4)
      (have-image star20 thermograph4)
      (have-image planet21 thermograph0)
      (have-image star22 thermograph3)
      (have-image planet23 image1)
    )
  )

  (:metric minimize (total-cost))
)
