(define (problem gripper-012-unit)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 ball16 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 1)
    (= (ball-cost ball2) 1)
    (= (ball-cost ball3) 1)
    (= (ball-cost ball4) 1)
    (= (ball-cost ball5) 1)
    (= (ball-cost ball6) 1)
    (= (ball-cost ball7) 1)
    (= (ball-cost ball8) 1)
    (= (ball-cost ball9) 1)
    (= (ball-cost ball10) 1)
    (= (ball-cost ball11) 1)
    (= (ball-cost ball12) 1)
    (= (ball-cost ball13) 1)
    (= (ball-cost ball14) 1)
    (= (ball-cost ball15) 1)
    (= (ball-cost ball16) 1)
    (at-robby room1)
    (free left)
    (free right)
    (at ball1 room1)
    (at ball2 room2)
    (at ball3 room0)
    (at ball4 room0)
    (at ball5 room1)
    (at ball6 room2)
    (at ball7 room1)
    (at ball8 room3)
    (at ball9 room1)
    (at ball10 room1)
    (at ball11 room1)
    (at ball12 room0)
    (at ball13 room3)
    (at ball14 room2)
    (at ball15 room1)
    (at ball16 room2)
  )

  (:goal
    (and
      (at ball1 room2)
      (at ball2 room3)
      (at ball3 room1)
      (at ball4 room3)
      (at ball5 room2)
      (at ball6 room0)
      (at ball7 room3)
      (at ball8 room0)
      (at ball9 room2)
      (at ball10 room0)
      (at ball11 room3)
      (at ball12 room3)
      (at ball13 room1)
      (at ball14 room3)
      (at ball15 room3)
      (at ball16 room0)
    )
  )

  (:metric minimize (total-cost))
)
