(define (problem gripper-081-unit)
  (:domain gripper)

  (:objects
    room0 room1 room2 room3 - room
    ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 ball16 ball17 ball18 - ball
    left right - gripper
  )

  (:init
    (= (total-cost) 0)
    (= (move-cost) 1)
    (= (ball-cost ball1) 1)
    (= (ball-cost ball2) 1)
    (= (ball-cost ball3) 1)
    (= (ball-cost ball4) 1)
    (= (ball-cost ball5) 1)
    (= (ball-cost ball6) 1)
    (= (ball-cost ball7) 1)
    (= (ball-cost ball8) 1)
    (= (ball-cost ball9) 1)
    (= (ball-cost ball10) 1)
    (= (ball-cost ball11) 1)
    (= (ball-cost ball12) 1)
    (= (ball-cost ball13) 1)
    (= (ball-cost ball14) 1)
    (= (ball-cost ball15) 1)
    (= (ball-cost ball16) 1)
    (= (ball-cost ball17) 1)
    (= (ball-cost ball18) 1)
    (at-robby room0)
    (free left)
    (free right)
    (at ball1 room2)
    (at ball2 room2)
    (at ball3 room3)
    (at ball4 room0)
    (at ball5 room3)
    (at ball6 room2)
    (at ball7 room2)
    (at ball8 room3)
    (at ball9 room0)
    (at ball10 room2)
    (at ball11 room2)
    (at ball12 room2)
    (at ball13 room1)
    (at ball14 room2)
    (at ball15 room2)
    (at ball16 room1)
    (at ball17 room0)
    (at ball18 room3)
  )

  (:goal
    (and
      (at ball1 room3)
      (at ball2 room3)
      (at ball3 room0)
      (at ball4 room2)
      (at ball5 room0)
      (at ball6 room3)
      (at ball7 room3)
      (at ball8 room2)
      (at ball9 room2)
      (at ball10 room3)
      (at ball11 room1)
      (at ball12 room1)
      (at ball13 room0)
      (at ball14 room3)
      (at ball15 room1)
      (at ball16 room3)
      (at ball17 room1)
      (at ball18 room2)
    )
  )

  (:metric minimize (total-cost))
)
