(define (problem satellite-ipc-017-unit)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 satellite5 satellite6 satellite7 satellite8 satellite9 satellite10 satellite11 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 instrument23 - instrument
    image0 image4 infrared2 infrared3 thermograph1 - mode
    groundstation0 groundstation2 groundstation4 phenomenon9 phenomenon14 phenomenon15 phenomenon17 phenomenon19 phenomenon20 phenomenon23 phenomenon24 planet5 planet6 planet7 planet11 planet12 planet13 planet16 star1 star3 star8 star10 star18 star21 star22 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 1)
    (= (target-cost groundstation2) 1)
    (= (target-cost groundstation4) 1)
    (= (target-cost phenomenon9) 1)
    (= (target-cost phenomenon14) 1)
    (= (target-cost phenomenon15) 1)
    (= (target-cost phenomenon17) 1)
    (= (target-cost phenomenon19) 1)
    (= (target-cost phenomenon20) 1)
    (= (target-cost phenomenon23) 1)
    (= (target-cost phenomenon24) 1)
    (= (target-cost planet5) 1)
    (= (target-cost planet6) 1)
    (= (target-cost planet7) 1)
    (= (target-cost planet11) 1)
    (= (target-cost planet12) 1)
    (= (target-cost planet13) 1)
    (= (target-cost planet16) 1)
    (= (target-cost star1) 1)
    (= (target-cost star3) 1)
    (= (target-cost star8) 1)
    (= (target-cost star10) 1)
    (= (target-cost star18) 1)
    (= (target-cost star21) 1)
    (= (target-cost star22) 1)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (instrument-cost instrument9) 1)
    (= (instrument-cost instrument10) 1)
    (= (instrument-cost instrument11) 1)
    (= (instrument-cost instrument12) 1)
    (= (instrument-cost instrument13) 1)
    (= (instrument-cost instrument14) 1)
    (= (instrument-cost instrument15) 1)
    (= (instrument-cost instrument16) 1)
    (= (instrument-cost instrument17) 1)
    (= (instrument-cost instrument18) 1)
    (= (instrument-cost instrument19) 1)
    (= (instrument-cost instrument20) 1)
    (= (instrument-cost instrument21) 1)
    (= (instrument-cost instrument22) 1)
    (= (instrument-cost instrument23) 1)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 1)
    (= (satellite-move-cost satellite4) 1)
    (= (satellite-move-cost satellite5) 1)
    (= (satellite-move-cost satellite6) 1)
    (= (satellite-move-cost satellite7) 1)
    (= (satellite-move-cost satellite8) 1)
    (= (satellite-move-cost satellite9) 1)
    (= (satellite-move-cost satellite10) 1)
    (= (satellite-move-cost satellite11) 1)
    (supports instrument0 infrared3)
    (calibration-target instrument0 groundstation0)
    (on-board instrument0 satellite0)
    (power-avail satellite0)
    (pointing satellite0 planet5)
    (supports instrument1 image0)
    (supports instrument1 infrared2)
    (calibration-target instrument1 star3)
    (supports instrument2 thermograph1)
    (supports instrument2 image0)
    (calibration-target instrument2 groundstation0)
    (on-board instrument1 satellite1)
    (on-board instrument2 satellite1)
    (power-avail satellite1)
    (pointing satellite1 planet5)
    (supports instrument3 infrared3)
    (supports instrument3 infrared2)
    (calibration-target instrument3 groundstation4)
    (supports instrument4 infrared3)
    (supports instrument4 infrared2)
    (supports instrument4 thermograph1)
    (calibration-target instrument4 groundstation2)
    (supports instrument5 thermograph1)
    (calibration-target instrument5 groundstation4)
    (on-board instrument3 satellite2)
    (on-board instrument4 satellite2)
    (on-board instrument5 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star21)
    (supports instrument6 image0)
    (supports instrument6 infrared2)
    (calibration-target instrument6 groundstation2)
    (supports instrument7 image0)
    (supports instrument7 infrared3)
    (calibration-target instrument7 groundstation0)
    (supports instrument8 infrared2)
    (supports instrument8 image4)
    (supports instrument8 image0)
    (calibration-target instrument8 groundstation4)
    (on-board instrument6 satellite3)
    (on-board instrument7 satellite3)
    (on-board instrument8 satellite3)
    (power-avail satellite3)
    (pointing satellite3 star21)
    (supports instrument9 infrared3)
    (calibration-target instrument9 star1)
    (supports instrument10 image4)
    (supports instrument10 image0)
    (calibration-target instrument10 star3)
    (on-board instrument9 satellite4)
    (on-board instrument10 satellite4)
    (power-avail satellite4)
    (pointing satellite4 star22)
    (supports instrument11 infrared2)
    (calibration-target instrument11 star1)
    (on-board instrument11 satellite5)
    (power-avail satellite5)
    (pointing satellite5 groundstation2)
    (supports instrument12 image4)
    (calibration-target instrument12 groundstation0)
    (supports instrument13 image4)
    (calibration-target instrument13 star1)
    (supports instrument14 thermograph1)
    (supports instrument14 infrared2)
    (calibration-target instrument14 groundstation2)
    (on-board instrument12 satellite6)
    (on-board instrument13 satellite6)
    (on-board instrument14 satellite6)
    (power-avail satellite6)
    (pointing satellite6 phenomenon20)
    (supports instrument15 image0)
    (supports instrument15 thermograph1)
    (calibration-target instrument15 groundstation4)
    (on-board instrument15 satellite7)
    (power-avail satellite7)
    (pointing satellite7 planet12)
    (supports instrument16 image0)
    (supports instrument16 infrared2)
    (calibration-target instrument16 star1)
    (supports instrument17 infrared3)
    (calibration-target instrument17 groundstation0)
    (on-board instrument16 satellite8)
    (on-board instrument17 satellite8)
    (power-avail satellite8)
    (pointing satellite8 phenomenon23)
    (supports instrument18 thermograph1)
    (supports instrument18 infrared2)
    (supports instrument18 image4)
    (calibration-target instrument18 star1)
    (supports instrument19 infrared3)
    (calibration-target instrument19 groundstation4)
    (on-board instrument18 satellite9)
    (on-board instrument19 satellite9)
    (power-avail satellite9)
    (pointing satellite9 phenomenon20)
    (supports instrument20 infrared2)
    (calibration-target instrument20 star1)
    (supports instrument21 thermograph1)
    (supports instrument21 image0)
    (calibration-target instrument21 star1)
    (supports instrument22 thermograph1)
    (calibration-target instrument22 groundstation0)
    (on-board instrument20 satellite10)
    (on-board instrument21 satellite10)
    (on-board instrument22 satellite10)
    (power-avail satellite10)
    (pointing satellite10 star22)
    (supports instrument23 infrared2)
    (supports instrument23 image4)
    (supports instrument23 thermograph1)
    (calibration-target instrument23 star3)
    (on-board instrument23 satellite11)
    (power-avail satellite11)
    (pointing satellite11 star8)
  )

  (:goal
    (and
      (pointing satellite1 star22)
      (pointing satellite4 phenomenon20)
      (pointing satellite8 planet16)
      (have-image planet5 image0)
      (have-image planet6 image4)
      (have-image planet7 image4)
      (have-image phenomenon9 image4)
      (have-image star10 thermograph1)
      (have-image planet11 image4)
      (have-image planet12 thermograph1)
      (have-image planet13 infrared3)
      (have-image phenomenon14 infrared2)
      (have-image phenomenon15 infrared2)
      (have-image planet16 infrared2)
      (have-image phenomenon17 thermograph1)
      (have-image star18 image4)
      (have-image star21 thermograph1)
      (have-image star22 image4)
      (have-image phenomenon23 infrared3)
      (have-image phenomenon24 infrared3)
    )
  )

  (:metric minimize (total-cost))
)
