(define (problem satellite-ipc-020-unit)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 instrument23 instrument24 instrument25 instrument26 instrument27 instrument28 - instrument
    image2 image3 image4 infrared1 infrared5 infrared9 spectrograph0 spectrograph6 thermograph7 thermograph8 - mode
    groundstation1 groundstation3 phenomenon5 phenomenon8 phenomenon12 phenomenon14 phenomenon19 phenomenon21 planet7 planet9 planet13 planet15 planet17 planet18 planet22 star0 star2 star4 star6 star10 star11 star16 star20 star23 star24 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation1) 1)
    (= (target-cost groundstation3) 1)
    (= (target-cost phenomenon5) 1)
    (= (target-cost phenomenon8) 1)
    (= (target-cost phenomenon12) 1)
    (= (target-cost phenomenon14) 1)
    (= (target-cost phenomenon19) 1)
    (= (target-cost phenomenon21) 1)
    (= (target-cost planet7) 1)
    (= (target-cost planet9) 1)
    (= (target-cost planet13) 1)
    (= (target-cost planet15) 1)
    (= (target-cost planet17) 1)
    (= (target-cost planet18) 1)
    (= (target-cost planet22) 1)
    (= (target-cost star0) 1)
    (= (target-cost star2) 1)
    (= (target-cost star4) 1)
    (= (target-cost star6) 1)
    (= (target-cost star10) 1)
    (= (target-cost star11) 1)
    (= (target-cost star16) 1)
    (= (target-cost star20) 1)
    (= (target-cost star23) 1)
    (= (target-cost star24) 1)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (instrument-cost instrument9) 1)
    (= (instrument-cost instrument10) 1)
    (= (instrument-cost instrument11) 1)
    (= (instrument-cost instrument12) 1)
    (= (instrument-cost instrument13) 1)
    (= (instrument-cost instrument14) 1)
    (= (instrument-cost instrument15) 1)
    (= (instrument-cost instrument16) 1)
    (= (instrument-cost instrument17) 1)
    (= (instrument-cost instrument18) 1)
    (= (instrument-cost instrument19) 1)
    (= (instrument-cost instrument20) 1)
    (= (instrument-cost instrument21) 1)
    (= (instrument-cost instrument22) 1)
    (= (instrument-cost instrument23) 1)
    (= (instrument-cost instrument24) 1)
    (= (instrument-cost instrument25) 1)
    (= (instrument-cost instrument26) 1)
    (= (instrument-cost instrument27) 1)
    (= (instrument-cost instrument28) 1)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 1)
    (= (satellite-move-cost satellite4) 1)
    (supports instrument0 image3)
    (calibration-target instrument0 star2)
    (supports instrument1 infrared9)
    (calibration-target instrument1 star4)
    (supports instrument2 thermograph8)
    (supports instrument2 image2)
    (supports instrument2 image4)
    (calibration-target instrument2 star4)
    (supports instrument3 infrared9)
    (calibration-target instrument3 star0)
    (supports instrument4 image3)
    (supports instrument4 thermograph8)
    (calibration-target instrument4 groundstation3)
    (supports instrument5 infrared9)
    (supports instrument5 image4)
    (calibration-target instrument5 groundstation3)
    (supports instrument6 infrared1)
    (calibration-target instrument6 groundstation3)
    (supports instrument7 thermograph8)
    (supports instrument7 spectrograph6)
    (calibration-target instrument7 groundstation1)
    (supports instrument8 spectrograph0)
    (supports instrument8 infrared9)
    (supports instrument8 thermograph7)
    (calibration-target instrument8 star2)
    (supports instrument9 thermograph7)
    (calibration-target instrument9 star4)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (on-board instrument3 satellite0)
    (on-board instrument4 satellite0)
    (on-board instrument5 satellite0)
    (on-board instrument6 satellite0)
    (on-board instrument7 satellite0)
    (on-board instrument8 satellite0)
    (on-board instrument9 satellite0)
    (power-avail satellite0)
    (pointing satellite0 groundstation1)
    (supports instrument10 infrared1)
    (supports instrument10 thermograph8)
    (supports instrument10 spectrograph6)
    (calibration-target instrument10 star4)
    (supports instrument11 image4)
    (supports instrument11 thermograph7)
    (supports instrument11 infrared1)
    (calibration-target instrument11 groundstation3)
    (supports instrument12 infrared9)
    (supports instrument12 thermograph8)
    (supports instrument12 infrared5)
    (calibration-target instrument12 groundstation3)
    (supports instrument13 image2)
    (supports instrument13 infrared1)
    (calibration-target instrument13 star4)
    (supports instrument14 image3)
    (calibration-target instrument14 groundstation3)
    (supports instrument15 thermograph7)
    (calibration-target instrument15 star2)
    (on-board instrument10 satellite1)
    (on-board instrument11 satellite1)
    (on-board instrument12 satellite1)
    (on-board instrument13 satellite1)
    (on-board instrument14 satellite1)
    (on-board instrument15 satellite1)
    (power-avail satellite1)
    (pointing satellite1 phenomenon19)
    (supports instrument16 infrared9)
    (supports instrument16 image2)
    (calibration-target instrument16 star4)
    (supports instrument17 infrared5)
    (calibration-target instrument17 star0)
    (supports instrument18 infrared9)
    (calibration-target instrument18 groundstation1)
    (supports instrument19 infrared5)
    (supports instrument19 image2)
    (calibration-target instrument19 groundstation3)
    (on-board instrument16 satellite2)
    (on-board instrument17 satellite2)
    (on-board instrument18 satellite2)
    (on-board instrument19 satellite2)
    (power-avail satellite2)
    (pointing satellite2 phenomenon14)
    (supports instrument20 image2)
    (supports instrument20 image3)
    (supports instrument20 image4)
    (calibration-target instrument20 groundstation1)
    (supports instrument21 image3)
    (supports instrument21 thermograph8)
    (supports instrument21 infrared5)
    (calibration-target instrument21 star2)
    (on-board instrument20 satellite3)
    (on-board instrument21 satellite3)
    (power-avail satellite3)
    (pointing satellite3 star10)
    (supports instrument22 thermograph8)
    (supports instrument22 infrared5)
    (calibration-target instrument22 star4)
    (supports instrument23 thermograph8)
    (supports instrument23 image3)
    (calibration-target instrument23 star2)
    (supports instrument24 thermograph8)
    (calibration-target instrument24 star2)
    (supports instrument25 infrared5)
    (calibration-target instrument25 star2)
    (supports instrument26 image3)
    (calibration-target instrument26 star4)
    (supports instrument27 image2)
    (supports instrument27 infrared9)
    (calibration-target instrument27 groundstation3)
    (supports instrument28 spectrograph0)
    (supports instrument28 image4)
    (supports instrument28 thermograph7)
    (calibration-target instrument28 groundstation1)
    (on-board instrument22 satellite4)
    (on-board instrument23 satellite4)
    (on-board instrument24 satellite4)
    (on-board instrument25 satellite4)
    (on-board instrument26 satellite4)
    (on-board instrument27 satellite4)
    (on-board instrument28 satellite4)
    (power-avail satellite4)
    (pointing satellite4 star16)
  )

  (:goal
    (and
      (pointing satellite1 phenomenon19)
      (have-image phenomenon5 thermograph8)
      (have-image phenomenon5 spectrograph0)
      (have-image phenomenon5 image3)
      (have-image star6 spectrograph0)
      (have-image star6 spectrograph6)
      (have-image star6 image3)
      (have-image planet7 spectrograph6)
      (have-image planet7 infrared5)
      (have-image planet7 image2)
      (have-image phenomenon8 spectrograph6)
      (have-image phenomenon8 infrared5)
      (have-image phenomenon8 thermograph7)
      (have-image planet9 spectrograph6)
      (have-image star10 spectrograph6)
      (have-image star11 thermograph7)
      (have-image star11 image4)
      (have-image star11 image3)
      (have-image phenomenon12 image4)
      (have-image planet13 infrared5)
      (have-image planet13 spectrograph6)
      (have-image planet13 image2)
      (have-image phenomenon14 thermograph7)
      (have-image planet15 image3)
      (have-image star16 image3)
      (have-image star16 image4)
      (have-image planet18 infrared9)
      (have-image planet18 infrared5)
      (have-image planet18 thermograph7)
      (have-image phenomenon19 image2)
      (have-image phenomenon19 image4)
      (have-image star20 spectrograph0)
      (have-image phenomenon21 image4)
      (have-image phenomenon21 image2)
      (have-image phenomenon21 thermograph7)
      (have-image planet22 image2)
      (have-image planet22 spectrograph6)
      (have-image star23 image2)
      (have-image star23 infrared9)
      (have-image star24 spectrograph6)
      (have-image star24 infrared5)
    )
  )

  (:metric minimize (total-cost))
)
