(define (problem satellite-ipc-006-unit)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 - instrument
    infrared1 infrared3 spectrograph0 thermograph2 - mode
    groundstation3 phenomenon8 planet4 planet5 star0 star1 star2 star6 star7 star9 star10 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation3) 1)
    (= (target-cost phenomenon8) 1)
    (= (target-cost planet4) 1)
    (= (target-cost planet5) 1)
    (= (target-cost star0) 1)
    (= (target-cost star1) 1)
    (= (target-cost star2) 1)
    (= (target-cost star6) 1)
    (= (target-cost star7) 1)
    (= (target-cost star9) 1)
    (= (target-cost star10) 1)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (supports instrument0 infrared1)
    (supports instrument0 spectrograph0)
    (calibration-target instrument0 star1)
    (on-board instrument0 satellite0)
    (power-avail satellite0)
    (pointing satellite0 phenomenon8)
    (supports instrument1 infrared3)
    (calibration-target instrument1 star2)
    (supports instrument2 infrared1)
    (supports instrument2 infrared3)
    (supports instrument2 thermograph2)
    (calibration-target instrument2 star2)
    (supports instrument3 infrared1)
    (supports instrument3 infrared3)
    (supports instrument3 spectrograph0)
    (calibration-target instrument3 star2)
    (on-board instrument1 satellite1)
    (on-board instrument2 satellite1)
    (on-board instrument3 satellite1)
    (power-avail satellite1)
    (pointing satellite1 star6)
    (supports instrument4 infrared3)
    (calibration-target instrument4 star0)
    (on-board instrument4 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star6)
  )

  (:goal
    (and
      (have-image planet4 thermograph2)
      (have-image planet5 spectrograph0)
      (have-image star6 thermograph2)
      (have-image star7 infrared3)
      (have-image phenomenon8 spectrograph0)
      (have-image star9 infrared1)
      (have-image star10 infrared3)
    )
  )

  (:metric minimize (total-cost))
)
