(define (problem satellite-ipc-012-unit)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 - instrument
    infrared0 infrared1 infrared3 spectrograph4 thermograph2 - mode
    groundstation1 phenomenon6 phenomenon13 phenomenon17 phenomenon21 phenomenon24 planet5 planet8 planet10 planet11 planet16 planet20 star0 star2 star3 star4 star7 star9 star12 star14 star15 star18 star19 star22 star23 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation1) 1)
    (= (target-cost phenomenon6) 1)
    (= (target-cost phenomenon13) 1)
    (= (target-cost phenomenon17) 1)
    (= (target-cost phenomenon21) 1)
    (= (target-cost phenomenon24) 1)
    (= (target-cost planet5) 1)
    (= (target-cost planet8) 1)
    (= (target-cost planet10) 1)
    (= (target-cost planet11) 1)
    (= (target-cost planet16) 1)
    (= (target-cost planet20) 1)
    (= (target-cost star0) 1)
    (= (target-cost star2) 1)
    (= (target-cost star3) 1)
    (= (target-cost star4) 1)
    (= (target-cost star7) 1)
    (= (target-cost star9) 1)
    (= (target-cost star12) 1)
    (= (target-cost star14) 1)
    (= (target-cost star15) 1)
    (= (target-cost star18) 1)
    (= (target-cost star19) 1)
    (= (target-cost star22) 1)
    (= (target-cost star23) 1)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (instrument-cost instrument9) 1)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 1)
    (= (satellite-move-cost satellite4) 1)
    (supports instrument0 infrared1)
    (supports instrument0 spectrograph4)
    (calibration-target instrument0 star0)
    (supports instrument1 infrared1)
    (supports instrument1 infrared0)
    (calibration-target instrument1 star2)
    (supports instrument2 infrared1)
    (supports instrument2 infrared0)
    (calibration-target instrument2 star3)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 planet16)
    (supports instrument3 infrared0)
    (supports instrument3 spectrograph4)
    (calibration-target instrument3 star4)
    (supports instrument4 infrared0)
    (supports instrument4 infrared3)
    (supports instrument4 thermograph2)
    (calibration-target instrument4 star4)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (power-avail satellite1)
    (pointing satellite1 star4)
    (supports instrument5 infrared1)
    (calibration-target instrument5 groundstation1)
    (on-board instrument5 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star15)
    (supports instrument6 infrared1)
    (calibration-target instrument6 star4)
    (on-board instrument6 satellite3)
    (power-avail satellite3)
    (pointing satellite3 phenomenon6)
    (supports instrument7 infrared1)
    (supports instrument7 infrared3)
    (calibration-target instrument7 star2)
    (supports instrument8 infrared0)
    (supports instrument8 infrared3)
    (supports instrument8 spectrograph4)
    (calibration-target instrument8 star2)
    (supports instrument9 infrared3)
    (supports instrument9 spectrograph4)
    (supports instrument9 infrared1)
    (calibration-target instrument9 star4)
    (on-board instrument7 satellite4)
    (on-board instrument8 satellite4)
    (on-board instrument9 satellite4)
    (power-avail satellite4)
    (pointing satellite4 star14)
  )

  (:goal
    (and
      (have-image planet5 infrared0)
      (have-image phenomenon6 spectrograph4)
      (have-image star7 infrared0)
      (have-image planet8 infrared1)
      (have-image star9 spectrograph4)
      (have-image planet10 thermograph2)
      (have-image planet11 infrared3)
      (have-image phenomenon13 spectrograph4)
      (have-image star14 thermograph2)
      (have-image star15 infrared3)
      (have-image planet16 infrared1)
      (have-image phenomenon17 spectrograph4)
      (have-image star18 spectrograph4)
      (have-image star19 thermograph2)
      (have-image planet20 thermograph2)
      (have-image phenomenon21 thermograph2)
      (have-image star22 infrared1)
      (have-image star23 spectrograph4)
      (have-image phenomenon24 infrared0)
    )
  )

  (:metric minimize (total-cost))
)
