(define (problem satellite-ipc-011-unit)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 - instrument
    image3 infrared0 infrared1 spectrograph4 thermograph2 - mode
    groundstation3 phenomenon7 phenomenon9 phenomenon15 planet6 planet13 planet14 planet16 planet19 star0 star1 star2 star4 star5 star8 star10 star11 star12 star17 star18 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation3) 1)
    (= (target-cost phenomenon7) 1)
    (= (target-cost phenomenon9) 1)
    (= (target-cost phenomenon15) 1)
    (= (target-cost planet6) 1)
    (= (target-cost planet13) 1)
    (= (target-cost planet14) 1)
    (= (target-cost planet16) 1)
    (= (target-cost planet19) 1)
    (= (target-cost star0) 1)
    (= (target-cost star1) 1)
    (= (target-cost star2) 1)
    (= (target-cost star4) 1)
    (= (target-cost star5) 1)
    (= (target-cost star8) 1)
    (= (target-cost star10) 1)
    (= (target-cost star11) 1)
    (= (target-cost star12) 1)
    (= (target-cost star17) 1)
    (= (target-cost star18) 1)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (= (satellite-move-cost satellite3) 1)
    (= (satellite-move-cost satellite4) 1)
    (supports instrument0 spectrograph4)
    (calibration-target instrument0 star0)
    (on-board instrument0 satellite0)
    (power-avail satellite0)
    (pointing satellite0 star8)
    (supports instrument1 infrared0)
    (supports instrument1 infrared1)
    (calibration-target instrument1 groundstation3)
    (supports instrument2 infrared1)
    (supports instrument2 infrared0)
    (calibration-target instrument2 star2)
    (supports instrument3 spectrograph4)
    (supports instrument3 infrared1)
    (supports instrument3 thermograph2)
    (calibration-target instrument3 star0)
    (on-board instrument1 satellite1)
    (on-board instrument2 satellite1)
    (on-board instrument3 satellite1)
    (power-avail satellite1)
    (pointing satellite1 groundstation3)
    (supports instrument4 infrared1)
    (supports instrument4 image3)
    (supports instrument4 infrared0)
    (calibration-target instrument4 star2)
    (supports instrument5 thermograph2)
    (supports instrument5 spectrograph4)
    (calibration-target instrument5 star0)
    (supports instrument6 infrared0)
    (calibration-target instrument6 groundstation3)
    (on-board instrument4 satellite2)
    (on-board instrument5 satellite2)
    (on-board instrument6 satellite2)
    (power-avail satellite2)
    (pointing satellite2 star4)
    (supports instrument7 image3)
    (calibration-target instrument7 star2)
    (on-board instrument7 satellite3)
    (power-avail satellite3)
    (pointing satellite3 phenomenon9)
    (supports instrument8 infrared0)
    (supports instrument8 spectrograph4)
    (supports instrument8 infrared1)
    (calibration-target instrument8 star2)
    (on-board instrument8 satellite4)
    (power-avail satellite4)
    (pointing satellite4 phenomenon9)
  )

  (:goal
    (and
      (pointing satellite0 phenomenon9)
      (pointing satellite1 star4)
      (pointing satellite4 star11)
      (have-image star5 image3)
      (have-image planet6 infrared1)
      (have-image phenomenon7 infrared1)
      (have-image star8 image3)
      (have-image star10 thermograph2)
      (have-image star11 infrared1)
      (have-image planet13 spectrograph4)
      (have-image planet14 thermograph2)
      (have-image phenomenon15 infrared0)
      (have-image planet16 image3)
      (have-image star17 infrared0)
    )
  )

  (:metric minimize (total-cost))
)
