(define (problem satellite-ipc-005-unit)
  (:domain satellite)

  (:objects
    satellite0 satellite1 satellite2 - satellite
    instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 - instrument
    image2 spectrograph1 thermograph0 - mode
    groundstation0 groundstation1 groundstation2 phenomenon5 phenomenon6 phenomenon8 planet9 star3 star4 star7 - direction
  )

  (:init
    (= (total-cost) 0)
    (= (target-cost groundstation0) 1)
    (= (target-cost groundstation1) 1)
    (= (target-cost groundstation2) 1)
    (= (target-cost phenomenon5) 1)
    (= (target-cost phenomenon6) 1)
    (= (target-cost phenomenon8) 1)
    (= (target-cost planet9) 1)
    (= (target-cost star3) 1)
    (= (target-cost star4) 1)
    (= (target-cost star7) 1)
    (= (instrument-cost instrument0) 1)
    (= (instrument-cost instrument1) 1)
    (= (instrument-cost instrument2) 1)
    (= (instrument-cost instrument3) 1)
    (= (instrument-cost instrument4) 1)
    (= (instrument-cost instrument5) 1)
    (= (instrument-cost instrument6) 1)
    (= (instrument-cost instrument7) 1)
    (= (instrument-cost instrument8) 1)
    (= (satellite-move-cost satellite0) 1)
    (= (satellite-move-cost satellite1) 1)
    (= (satellite-move-cost satellite2) 1)
    (supports instrument0 image2)
    (supports instrument0 thermograph0)
    (supports instrument0 spectrograph1)
    (calibration-target instrument0 groundstation2)
    (supports instrument1 thermograph0)
    (supports instrument1 spectrograph1)
    (supports instrument1 image2)
    (calibration-target instrument1 groundstation1)
    (supports instrument2 image2)
    (calibration-target instrument2 groundstation0)
    (on-board instrument0 satellite0)
    (on-board instrument1 satellite0)
    (on-board instrument2 satellite0)
    (power-avail satellite0)
    (pointing satellite0 phenomenon8)
    (supports instrument3 spectrograph1)
    (supports instrument3 thermograph0)
    (calibration-target instrument3 groundstation0)
    (supports instrument4 image2)
    (supports instrument4 spectrograph1)
    (calibration-target instrument4 groundstation2)
    (supports instrument5 image2)
    (supports instrument5 spectrograph1)
    (supports instrument5 thermograph0)
    (calibration-target instrument5 groundstation1)
    (on-board instrument3 satellite1)
    (on-board instrument4 satellite1)
    (on-board instrument5 satellite1)
    (power-avail satellite1)
    (pointing satellite1 groundstation2)
    (supports instrument6 image2)
    (calibration-target instrument6 groundstation1)
    (supports instrument7 image2)
    (supports instrument7 thermograph0)
    (calibration-target instrument7 groundstation1)
    (supports instrument8 spectrograph1)
    (supports instrument8 image2)
    (supports instrument8 thermograph0)
    (calibration-target instrument8 groundstation0)
    (on-board instrument6 satellite2)
    (on-board instrument7 satellite2)
    (on-board instrument8 satellite2)
    (power-avail satellite2)
    (pointing satellite2 phenomenon5)
  )

  (:goal
    (and
      (pointing satellite0 phenomenon5)
      (pointing satellite1 groundstation2)
      (have-image star3 thermograph0)
      (have-image phenomenon5 image2)
      (have-image phenomenon6 image2)
      (have-image star7 thermograph0)
      (have-image phenomenon8 image2)
      (have-image planet9 spectrograph1)
    )
  )

  (:metric minimize (total-cost))
)
