(define (problem zenotravel-ipc-016-inverse)
  (:domain zenotravel)

  (:objects
    city0 city1 city2 city3 city4 city5 city6 city7 city8 city9 city10 city11 city12 city13 - city
    plane1 plane2 plane3 plane4 plane5 - aircraft
    person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 - person
  )

  (:init
    (= (total-cost) 0)
    (= (person-cost person1) 15)
    (= (person-cost person2) 14)
    (= (person-cost person3) 13)
    (= (person-cost person4) 12)
    (= (person-cost person5) 11)
    (= (person-cost person6) 10)
    (= (person-cost person7) 9)
    (= (person-cost person8) 8)
    (= (person-cost person9) 7)
    (= (person-cost person10) 6)
    (= (person-cost person11) 5)
    (= (person-cost person12) 4)
    (= (person-cost person13) 3)
    (= (person-cost person14) 2)
    (= (person-cost person15) 1)
    (= (fly-cost) 1)
    (= (zoom-cost) 1)
    (at-aircraft plane1 city6)
    (at-aircraft plane2 city0)
    (at-aircraft plane3 city10)
    (at-aircraft plane4 city4)
    (at-aircraft plane5 city1)
    (at-person person1 city8)
    (at-person person2 city12)
    (at-person person3 city0)
    (at-person person4 city4)
    (at-person person5 city13)
    (at-person person6 city7)
    (at-person person7 city1)
    (at-person person8 city2)
    (at-person person9 city1)
    (at-person person10 city2)
    (at-person person11 city10)
    (at-person person12 city7)
    (at-person person13 city6)
    (at-person person14 city1)
    (at-person person15 city13)
  )

  (:goal
    (and
      (at-aircraft plane2 city12)
      (at-aircraft plane3 city6)
      (at-person person1 city3)
      (at-person person2 city4)
      (at-person person3 city11)
      (at-person person4 city13)
      (at-person person5 city11)
      (at-person person6 city7)
      (at-person person7 city1)
      (at-person person8 city11)
      (at-person person9 city2)
      (at-person person10 city6)
      (at-person person11 city0)
      (at-person person12 city12)
      (at-person person13 city13)
      (at-person person14 city4)
      (at-person person15 city4)
    )
  )

  (:metric minimize (total-cost))
)
