(define (problem rovers-ipc-006-heavy)
  (:domain rovers)

  (:objects
    rover0 rover1 - rover
    waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
    rover0store rover1store - store
    camera0 camera1 camera2 - camera
    colour high_res low_res - mode
    objective0 objective1 - objective
    general - lander
  )

  (:init
    (= (total-cost) 0)
    (= (sample-cost waypoint0) 1)
    (= (sample-cost waypoint1) 1)
    (= (sample-cost waypoint2) 1)
    (= (sample-cost waypoint3) 1)
    (= (sample-cost waypoint4) 10)
    (= (sample-cost waypoint5) 10)
    (= (image-cost objective0) 1)
    (= (image-cost objective1) 10)
    (= (rover-cost rover0) 1)
    (= (rover-cost rover1) 10)
    (= (communicate-cost) 1)
    (visible waypoint0 waypoint3)
    (visible waypoint3 waypoint0)
    (visible waypoint1 waypoint0)
    (visible waypoint0 waypoint1)
    (visible waypoint1 waypoint4)
    (visible waypoint4 waypoint1)
    (visible waypoint2 waypoint0)
    (visible waypoint0 waypoint2)
    (visible waypoint2 waypoint3)
    (visible waypoint3 waypoint2)
    (visible waypoint3 waypoint1)
    (visible waypoint1 waypoint3)
    (visible waypoint3 waypoint5)
    (visible waypoint5 waypoint3)
    (visible waypoint4 waypoint3)
    (visible waypoint3 waypoint4)
    (visible waypoint5 waypoint0)
    (visible waypoint0 waypoint5)
    (visible waypoint5 waypoint2)
    (visible waypoint2 waypoint5)
    (visible waypoint5 waypoint4)
    (visible waypoint4 waypoint5)
    (at-lander general waypoint3)
    (channel-free general)
    (at rover0 waypoint1)
    (store-of rover0store rover0)
    (empty rover0store)
    (equipped-for-rock-analysis rover0)
    (equipped-for-imaging rover0)
    (can-traverse rover0 waypoint1 waypoint0)
    (can-traverse rover0 waypoint0 waypoint1)
    (can-traverse rover0 waypoint1 waypoint4)
    (can-traverse rover0 waypoint4 waypoint1)
    (can-traverse rover0 waypoint0 waypoint2)
    (can-traverse rover0 waypoint2 waypoint0)
    (can-traverse rover0 waypoint0 waypoint3)
    (can-traverse rover0 waypoint3 waypoint0)
    (can-traverse rover0 waypoint0 waypoint5)
    (can-traverse rover0 waypoint5 waypoint0)
    (at rover1 waypoint4)
    (store-of rover1store rover1)
    (empty rover1store)
    (equipped-for-soil-analysis rover1)
    (equipped-for-imaging rover1)
    (can-traverse rover1 waypoint4 waypoint1)
    (can-traverse rover1 waypoint1 waypoint4)
    (can-traverse rover1 waypoint4 waypoint3)
    (can-traverse rover1 waypoint3 waypoint4)
    (can-traverse rover1 waypoint4 waypoint5)
    (can-traverse rover1 waypoint5 waypoint4)
    (can-traverse rover1 waypoint1 waypoint0)
    (can-traverse rover1 waypoint0 waypoint1)
    (can-traverse rover1 waypoint5 waypoint2)
    (can-traverse rover1 waypoint2 waypoint5)
    (on-board camera0 rover0)
    (calibration-target camera0 objective0)
    (supports camera0 colour)
    (supports camera0 low_res)
    (on-board camera1 rover0)
    (calibration-target camera1 objective1)
    (supports camera1 colour)
    (supports camera1 low_res)
    (on-board camera2 rover1)
    (calibration-target camera2 objective0)
    (supports camera2 colour)
    (supports camera2 high_res)
    (visible-from objective0 waypoint0)
    (visible-from objective0 waypoint1)
    (visible-from objective0 waypoint2)
    (visible-from objective0 waypoint3)
    (visible-from objective0 waypoint4)
    (visible-from objective0 waypoint5)
    (visible-from objective1 waypoint0)
    (visible-from objective1 waypoint1)
  )

  (:goal
    (and
      (communicated-soil-data waypoint5)
      (communicated-soil-data waypoint1)
      (communicated-soil-data waypoint4)
      (communicated-soil-data waypoint2)
      (communicated-rock-data waypoint0)
      (communicated-rock-data waypoint2)
      (communicated-rock-data waypoint3)
      (communicated-image-data objective0 colour)
      (communicated-image-data objective1 low_res)
      (communicated-image-data objective0 low_res)
    )
  )

  (:metric minimize (total-cost))
)
