(define (problem depots-ipc-021-heavy)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 depot3 depot4 depot5 distributor0 distributor1 distributor2 distributor3 distributor4 distributor5 - place
    truck0 truck1 truck2 truck3 truck4 truck5 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 hoist10 hoist11 hoist12 hoist13 hoist14 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 pallet10 pallet11 pallet12 pallet13 pallet14 pallet15 pallet16 pallet17 pallet18 pallet19 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 1)
    (= (crate-cost crate2) 1)
    (= (crate-cost crate3) 1)
    (= (crate-cost crate4) 1)
    (= (crate-cost crate5) 1)
    (= (crate-cost crate6) 1)
    (= (crate-cost crate7) 10)
    (= (crate-cost crate8) 10)
    (= (crate-cost crate9) 10)
    (= (drive-cost) 1)
    (clear crate1)
    (clear crate5)
    (clear pallet2)
    (clear pallet3)
    (clear crate6)
    (clear pallet5)
    (clear pallet6)
    (clear crate8)
    (clear crate4)
    (clear pallet9)
    (clear pallet10)
    (clear pallet11)
    (clear pallet12)
    (clear crate2)
    (clear pallet14)
    (clear crate3)
    (clear crate0)
    (clear pallet17)
    (clear crate7)
    (clear crate9)
    (at-truck truck0 distributor2)
    (at-truck truck1 depot0)
    (at-truck truck2 distributor3)
    (at-truck truck3 distributor0)
    (at-truck truck4 depot0)
    (at-truck truck5 depot4)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 depot3)
    (available hoist3)
    (at-hoist hoist4 depot4)
    (available hoist4)
    (at-hoist hoist5 depot5)
    (available hoist5)
    (at-hoist hoist6 distributor0)
    (available hoist6)
    (at-hoist hoist7 distributor1)
    (available hoist7)
    (at-hoist hoist8 distributor2)
    (available hoist8)
    (at-hoist hoist9 distributor3)
    (available hoist9)
    (at-hoist hoist10 distributor4)
    (available hoist10)
    (at-hoist hoist11 distributor5)
    (available hoist11)
    (at-hoist hoist12 depot5)
    (available hoist12)
    (at-hoist hoist13 depot1)
    (available hoist13)
    (at-hoist hoist14 depot4)
    (available hoist14)
    (at-crate crate0 depot1)
    (on crate0 pallet16)
    (at-crate crate1 depot0)
    (on crate1 pallet0)
    (at-crate crate2 distributor5)
    (on crate2 pallet13)
    (at-crate crate3 depot1)
    (on crate3 pallet15)
    (at-crate crate4 distributor2)
    (on crate4 pallet8)
    (at-crate crate5 depot1)
    (on crate5 pallet1)
    (at-crate crate6 depot4)
    (on crate6 pallet4)
    (at-crate crate7 depot4)
    (on crate7 pallet18)
    (at-crate crate8 distributor1)
    (on crate8 pallet7)
    (at-crate crate9 depot1)
    (on crate9 pallet19)
  )

  (:goal
    (and
      (on crate0 pallet2)
      (on crate1 pallet7)
      (on crate2 pallet11)
      (on crate3 pallet3)
      (on crate5 pallet5)
      (on crate6 pallet12)
      (on crate7 pallet18)
      (on crate8 pallet15)
    )
  )

  (:metric minimize (total-cost))
)
