(define (problem depots-ipc-022-heavy)
  (:domain depots)

  (:objects
    depot0 depot1 depot2 depot3 depot4 depot5 distributor0 distributor1 distributor2 distributor3 distributor4 distributor5 - place
    truck0 truck1 truck2 truck3 truck4 truck5 - truck
    hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 hoist10 hoist11 hoist12 hoist13 hoist14 - hoist
    pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 pallet10 pallet11 pallet12 pallet13 pallet14 pallet15 pallet16 pallet17 pallet18 pallet19 - surface
    crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 crate15 crate16 crate17 crate18 crate19 - crate
  )

  (:init
    (= (total-cost) 0)
    (= (crate-cost crate0) 1)
    (= (crate-cost crate1) 1)
    (= (crate-cost crate2) 1)
    (= (crate-cost crate3) 1)
    (= (crate-cost crate4) 1)
    (= (crate-cost crate5) 1)
    (= (crate-cost crate6) 1)
    (= (crate-cost crate7) 1)
    (= (crate-cost crate8) 1)
    (= (crate-cost crate9) 1)
    (= (crate-cost crate10) 1)
    (= (crate-cost crate11) 1)
    (= (crate-cost crate12) 1)
    (= (crate-cost crate13) 1)
    (= (crate-cost crate14) 1)
    (= (crate-cost crate15) 10)
    (= (crate-cost crate16) 10)
    (= (crate-cost crate17) 10)
    (= (crate-cost crate18) 10)
    (= (crate-cost crate19) 10)
    (= (drive-cost) 1)
    (clear crate10)
    (clear crate17)
    (clear pallet2)
    (clear pallet3)
    (clear pallet4)
    (clear crate8)
    (clear pallet6)
    (clear crate19)
    (clear crate13)
    (clear crate16)
    (clear crate14)
    (clear crate0)
    (clear crate18)
    (clear crate15)
    (clear pallet14)
    (clear pallet15)
    (clear pallet16)
    (clear crate6)
    (clear pallet18)
    (clear pallet19)
    (at-truck truck0 depot2)
    (at-truck truck1 distributor4)
    (at-truck truck2 distributor2)
    (at-truck truck3 depot0)
    (at-truck truck4 distributor3)
    (at-truck truck5 distributor0)
    (at-hoist hoist0 depot0)
    (available hoist0)
    (at-hoist hoist1 depot1)
    (available hoist1)
    (at-hoist hoist2 depot2)
    (available hoist2)
    (at-hoist hoist3 depot3)
    (available hoist3)
    (at-hoist hoist4 depot4)
    (available hoist4)
    (at-hoist hoist5 depot5)
    (available hoist5)
    (at-hoist hoist6 distributor0)
    (available hoist6)
    (at-hoist hoist7 distributor1)
    (available hoist7)
    (at-hoist hoist8 distributor2)
    (available hoist8)
    (at-hoist hoist9 distributor3)
    (available hoist9)
    (at-hoist hoist10 distributor4)
    (available hoist10)
    (at-hoist hoist11 distributor5)
    (available hoist11)
    (at-hoist hoist12 depot0)
    (available hoist12)
    (at-hoist hoist13 depot5)
    (available hoist13)
    (at-hoist hoist14 depot5)
    (available hoist14)
    (at-crate crate0 distributor5)
    (on crate0 pallet11)
    (at-crate crate1 depot0)
    (on crate1 pallet0)
    (at-crate crate2 distributor4)
    (on crate2 pallet10)
    (at-crate crate3 distributor2)
    (on crate3 pallet8)
    (at-crate crate4 distributor1)
    (on crate4 pallet7)
    (at-crate crate5 distributor4)
    (on crate5 crate2)
    (at-crate crate6 distributor2)
    (on crate6 pallet17)
    (at-crate crate7 depot5)
    (on crate7 pallet5)
    (at-crate crate8 depot5)
    (on crate8 crate7)
    (at-crate crate9 depot0)
    (on crate9 crate1)
    (at-crate crate10 depot0)
    (on crate10 crate9)
    (at-crate crate11 distributor3)
    (on crate11 pallet9)
    (at-crate crate12 depot1)
    (on crate12 pallet1)
    (at-crate crate13 distributor2)
    (on crate13 crate3)
    (at-crate crate14 distributor4)
    (on crate14 crate5)
    (at-crate crate15 distributor2)
    (on crate15 pallet13)
    (at-crate crate16 distributor3)
    (on crate16 crate11)
    (at-crate crate17 depot1)
    (on crate17 crate12)
    (at-crate crate18 distributor4)
    (on crate18 pallet12)
    (at-crate crate19 distributor1)
    (on crate19 crate4)
  )

  (:goal
    (and
      (on crate0 pallet14)
      (on crate1 pallet15)
      (on crate2 pallet13)
      (on crate3 pallet18)
      (on crate5 pallet12)
      (on crate6 pallet6)
      (on crate7 pallet5)
      (on crate8 crate10)
      (on crate9 pallet17)
      (on crate10 crate17)
      (on crate11 pallet1)
      (on crate12 pallet16)
      (on crate13 crate16)
      (on crate15 pallet7)
      (on crate16 crate15)
      (on crate17 pallet2)
      (on crate18 pallet4)
      (on crate19 pallet9)
    )
  )

  (:metric minimize (total-cost))
)
