(define (problem miconic-ipc-025-heavy)
  (:domain miconic)

  (:objects
    f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 - floor
    p0 p1 p2 p3 p4 - passenger
  )

  (:init
    (= (total-cost) 0)
    (= (passenger-cost p0) 1)
    (= (passenger-cost p1) 1)
    (= (passenger-cost p2) 1)
    (= (passenger-cost p3) 10)
    (= (passenger-cost p4) 10)
    (= (move-cost) 1)
    (above f1 f0)
    (above f2 f0)
    (above f3 f0)
    (above f4 f0)
    (above f5 f0)
    (above f6 f0)
    (above f7 f0)
    (above f8 f0)
    (above f9 f0)
    (above f2 f1)
    (above f3 f1)
    (above f4 f1)
    (above f5 f1)
    (above f6 f1)
    (above f7 f1)
    (above f8 f1)
    (above f9 f1)
    (above f3 f2)
    (above f4 f2)
    (above f5 f2)
    (above f6 f2)
    (above f7 f2)
    (above f8 f2)
    (above f9 f2)
    (above f4 f3)
    (above f5 f3)
    (above f6 f3)
    (above f7 f3)
    (above f8 f3)
    (above f9 f3)
    (above f5 f4)
    (above f6 f4)
    (above f7 f4)
    (above f8 f4)
    (above f9 f4)
    (above f6 f5)
    (above f7 f5)
    (above f8 f5)
    (above f9 f5)
    (above f7 f6)
    (above f8 f6)
    (above f9 f6)
    (above f8 f7)
    (above f9 f7)
    (above f9 f8)
    (origin p0 f5)
    (destin p0 f1)
    (origin p1 f2)
    (destin p1 f0)
    (origin p2 f2)
    (destin p2 f8)
    (origin p3 f7)
    (destin p3 f5)
    (origin p4 f9)
    (destin p4 f4)
    (lift-at f0)
  )

  (:goal
    (and
      (served p0)
      (served p1)
      (served p2)
      (served p3)
      (served p4)
    )
  )

  (:metric minimize (total-cost))
)
