(define (problem miconic-ipc-018-heavy)
  (:domain miconic)

  (:objects
    f0 f1 f2 f3 f4 f5 f6 f7 - floor
    p0 p1 p2 p3 - passenger
  )

  (:init
    (= (total-cost) 0)
    (= (passenger-cost p0) 1)
    (= (passenger-cost p1) 1)
    (= (passenger-cost p2) 1)
    (= (passenger-cost p3) 10)
    (= (move-cost) 1)
    (above f1 f0)
    (above f2 f0)
    (above f3 f0)
    (above f4 f0)
    (above f5 f0)
    (above f6 f0)
    (above f7 f0)
    (above f2 f1)
    (above f3 f1)
    (above f4 f1)
    (above f5 f1)
    (above f6 f1)
    (above f7 f1)
    (above f3 f2)
    (above f4 f2)
    (above f5 f2)
    (above f6 f2)
    (above f7 f2)
    (above f4 f3)
    (above f5 f3)
    (above f6 f3)
    (above f7 f3)
    (above f5 f4)
    (above f6 f4)
    (above f7 f4)
    (above f6 f5)
    (above f7 f5)
    (above f7 f6)
    (origin p0 f3)
    (destin p0 f0)
    (origin p1 f4)
    (destin p1 f2)
    (origin p2 f1)
    (destin p2 f6)
    (origin p3 f6)
    (destin p3 f7)
    (lift-at f0)
  )

  (:goal
    (and
      (served p0)
      (served p1)
      (served p2)
      (served p3)
    )
  )

  (:metric minimize (total-cost))
)
