(define (problem driverlog-ipc-009-inverse)
  (:domain driverlog)

  (:objects
    p0-1 p1-2 p1-3 p3-2 p3-4 p4-0 s0 s1 s2 s3 s4 - location
    truck1 truck2 truck3 - truck
    driver1 driver2 - driver
    package1 package2 package3 package4 package5 package6 - package
  )

  (:init
    (= (total-cost) 0)
    (= (package-cost package1) 6)
    (= (package-cost package2) 5)
    (= (package-cost package3) 4)
    (= (package-cost package4) 3)
    (= (package-cost package5) 2)
    (= (package-cost package6) 1)
    (= (driver-cost driver1) 2)
    (= (driver-cost driver2) 1)
    (= (drive-cost) 1)
    (= (walk-cost) 1)
    (at-driver driver1 s4)
    (at-driver driver2 s1)
    (at-truck truck1 s2)
    (empty truck1)
    (at-truck truck2 s0)
    (empty truck2)
    (at-truck truck3 s3)
    (empty truck3)
    (at-package package1 s2)
    (at-package package2 s1)
    (at-package package3 s3)
    (at-package package4 s0)
    (at-package package5 s1)
    (at-package package6 s1)
    (path s0 p0-1)
    (path p0-1 s0)
    (path s1 p0-1)
    (path p0-1 s1)
    (path s1 p1-2)
    (path p1-2 s1)
    (path s2 p1-2)
    (path p1-2 s2)
    (path s1 p1-3)
    (path p1-3 s1)
    (path s3 p1-3)
    (path p1-3 s3)
    (path s3 p3-2)
    (path p3-2 s3)
    (path s2 p3-2)
    (path p3-2 s2)
    (path s3 p3-4)
    (path p3-4 s3)
    (path s4 p3-4)
    (path p3-4 s4)
    (path s4 p4-0)
    (path p4-0 s4)
    (path s0 p4-0)
    (path p4-0 s0)
    (link s0 s2)
    (link s2 s0)
    (link s0 s3)
    (link s3 s0)
    (link s1 s0)
    (link s0 s1)
    (link s2 s1)
    (link s1 s2)
    (link s3 s2)
    (link s2 s3)
    (link s4 s0)
    (link s0 s4)
    (link s4 s2)
    (link s2 s4)
    (link s4 s3)
    (link s3 s4)
  )

  (:goal
    (and
      (at-driver driver1 s3)
      (at-driver driver2 s4)
      (at-truck truck1 s3)
      (at-truck truck2 s3)
      (at-package package1 s3)
      (at-package package2 s2)
      (at-package package3 s1)
      (at-package package4 s0)
      (at-package package5 s1)
      (at-package package6 s1)
    )
  )

  (:metric minimize (total-cost))
)
